/*
 * Jelly5 — Jellyfin for PS5
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Generated from the Unicode CLDR (via Babel) and ISO 639 (via pycountry): long
 * dates and language names in each of the interface's languages. CLDR data:
 * Copyright © 2004-2025 Unicode, Inc., Unicode License v3 (CLDR-LICENSE.txt). Don't edit by hand.
 */
#include "app/i18n_cldr.h"

#include <cstdio>
#include <cstring>

namespace i18n {
namespace {

struct DateFormat {
    const char *pattern;   /* {d} day, {m} month number, {M} month name, {y} year, {b} Buddhist year */
    const char *months[12];
};

const DateFormat kDates[(int)Lang::Count] = {
    /* Norwegian */ {"{d}. {M} {y}", {"januar", "februar", "mars", "april", "mai", "juni", "juli", "august", "september", "oktober", "november", "desember"}},
    /* English */ {"{M} {d}, {y}", {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"}},
    /* Spanish */ {"{d} de {M} de {y}", {"enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"}},
    /* French */ {"{d} {M} {y}", {"janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"}},
    /* German */ {"{d}. {M} {y}", {"Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"}},
    /* Portuguese */ {"{d} de {M} de {y}", {"janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"}},
    /* Italian */ {"{d} {M} {y}", {"gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"}},
    /* Japanese */ {"{y}年{m}月{d}日", {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"}},
    /* Dutch */ {"{d} {M} {y}", {"januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"}},
    /* Russian */ {"{d} {M} {y} г.", {"января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"}},
    /* Korean */ {"{y}년 {M} {d}일", {"1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"}},
    /* ChineseTraditional */ {"{y}年{m}月{d}日", {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"}},
    /* ChineseSimplified */ {"{y}年{m}月{d}日", {"一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"}},
    /* Finnish */ {"{d}. {M} {y}", {"tammikuuta", "helmikuuta", "maaliskuuta", "huhtikuuta", "toukokuuta", "kesäkuuta", "heinäkuuta", "elokuuta", "syyskuuta", "lokakuuta", "marraskuuta", "joulukuuta"}},
    /* Swedish */ {"{d} {M} {y}", {"januari", "februari", "mars", "april", "maj", "juni", "juli", "augusti", "september", "oktober", "november", "december"}},
    /* Danish */ {"{d}. {M} {y}", {"januar", "februar", "marts", "april", "maj", "juni", "juli", "august", "september", "oktober", "november", "december"}},
    /* Polish */ {"{d} {M} {y}", {"stycznia", "lutego", "marca", "kwietnia", "maja", "czerwca", "lipca", "sierpnia", "września", "października", "listopada", "grudnia"}},
    /* Turkish */ {"{d} {M} {y}", {"Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"}},
    /* Arabic */ {"{d} {M} {y}", {"يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"}},
    /* Czech */ {"{d}. {M} {y}", {"ledna", "února", "března", "dubna", "května", "června", "července", "srpna", "září", "října", "listopadu", "prosince"}},
    /* Hungarian */ {"{y}. {M} {d}.", {"január", "február", "március", "április", "május", "június", "július", "augusztus", "szeptember", "október", "november", "december"}},
    /* Greek */ {"{d} {M} {y}", {"Ιανουαρίου", "Φεβρουαρίου", "Μαρτίου", "Απριλίου", "Μαΐου", "Ιουνίου", "Ιουλίου", "Αυγούστου", "Σεπτεμβρίου", "Οκτωβρίου", "Νοεμβρίου", "Δεκεμβρίου"}},
    /* Romanian */ {"{d} {M} {y}", {"ianuarie", "februarie", "martie", "aprilie", "mai", "iunie", "iulie", "august", "septembrie", "octombrie", "noiembrie", "decembrie"}},
    /* Thai */ {"{d} {M} พ.ศ. {b}", {"มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"}},
    /* Vietnamese */ {"{d} {M}, {y}", {"tháng 1", "tháng 2", "tháng 3", "tháng 4", "tháng 5", "tháng 6", "tháng 7", "tháng 8", "tháng 9", "tháng 10", "tháng 11", "tháng 12"}},
    /* Indonesian */ {"{d} {M} {y}", {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"}},
    /* Ukrainian */ {"{d} {M} {y} р.", {"січня", "лютого", "березня", "квітня", "травня", "червня", "липня", "серпня", "вересня", "жовтня", "листопада", "грудня"}},
};

struct LanguageName {
    const char *codes;   /* ISO 639-1, -2/T, -2/B */
    const char *names[(int)Lang::Count];
};

const LanguageName kLanguages[] = {
    {"aa aar", {"Afar", "Afar", "Afar", "Afar", "Afar", "Afar", "Afar", "アファル語", "Afar", "Афарский", "아파르어", "阿法文", "阿法尔语", "Afar", "Afar", "Afar", "Afar", "Afar", "الأفارية", "Afarština", "Afar", "Αφάρ", "Afar", "อะฟาร์", "Tiếng Afar", "Afar", "Афарська"}},
    {"ab abk", {"Abkhasisk", "Abkhazian", "Abjasio", "Abkhaze", "Abchasisch", "Abcázio", "Abcaso", "アブハズ語", "Abchazisch", "Абхазский", "압카즈어", "阿布哈茲文", "阿布哈西亚语", "Abhaasi", "Abchaziska", "Abkhasisk", "Abchaski", "Abhazca", "الأبخازية", "Abcházština", "Abház", "Αμπχαζικά", "Abhază", "อับฮาเซีย", "Tiếng Abkhazia", "Abkhaz", "Абхазька"}},
    {"af afr", {"Afrikaans", "Afrikaans", "Afrikáans", "Afrikaans", "Afrikaans", "Africâner", "Afrikaans", "アフリカーンス語", "Afrikaans", "Африкаанс", "아프리칸스어", "南非荷蘭文", "南非荷兰语", "Afrikaans", "Afrikaans", "Afrikaans", "Afrikaans", "Afrikaanca", "الأفريقانية", "Afrikánština", "Afrikaans", "Αφρικάανς", "Afrikaans", "แอฟริกานส์", "Tiếng Hà Lan (Nam Phi)", "Afrikaans", "Африкаанс"}},
    {"ak aka", {"Akan", "Akan", "Akan", "Akan", "Akan", "Akan", "Akan", "アカン語", "Akan", "Акан", "아칸어", "阿坎文", "阿肯语", "Akan", "Akan", "Akan", "Akan", "Akan", "الأكانية", "Akanština", "Akan", "Ακάν", "Akan", "อาคาน", "Tiếng Akan", "Akan", "Акан"}},
    {"am amh", {"Amharisk", "Amharic", "Amárico", "Amharique", "Amharisch", "Amárico", "Amarico", "アムハラ語", "Amhaars", "Амхарский", "암하라어", "阿姆哈拉文", "阿姆哈拉语", "Amhara", "Amhariska", "Amharisk", "Amharski", "Amharca", "الأمهرية", "Amharština", "Amhara", "Αμχαρικά", "Amharică", "อัมฮารา", "Tiếng Amharic", "Amharik", "Амхарська"}},
    {"ar ara", {"Arabisk", "Arabic", "Árabe", "Arabe", "Arabisch", "Árabe", "Arabo", "アラビア語", "Arabisch", "Арабский", "아랍어", "阿拉伯文", "阿拉伯语", "Arabia", "Arabiska", "Arabisk", "Arabski", "Arapça", "العربية", "Arabština", "Arab", "Αραβικά", "Arabă", "อาหรับ", "Tiếng Ả Rập", "Arab", "Арабська"}},
    {"an arg", {"Aragonsk", "Aragonese", "Aragonés", "Aragonais", "Aragonesisch", "Aragonês", "Aragonese", "アラゴン語", "Aragonees", "Арагонский", "아라곤어", "阿拉貢文", "阿拉贡语", "Aragonia", "Aragonesiska", "Aragonsk", "Aragoński", "Aragonca", "الأراغونية", "Aragonština", "Aragonéz", "Αραγονικά", "Aragoneză", "อารากอน", "Tiếng Aragon", "Aragon", "Арагонська"}},
    {"as asm", {"Assamesisk", "Assamese", "Asamés", "Assamais", "Assamesisch", "Assamês", "Assamese", "アッサム語", "Assamees", "Ассамский", "아삼어", "阿薩姆文", "阿萨姆语", "Assami", "Assamesiska", "Assamesisk", "Asamski", "Assamca", "الأسامية", "Ásámština", "Asszámi", "Ασαμικά", "Asameză", "อัสสัม", "Tiếng Assam", "Assam", "Асамська"}},
    {"av ava", {"Avarisk", "Avaric", "Avar", "Avar", "Awarisch", "Avárico", "Avaro", "アヴァル語", "Avarisch", "Аварский", "아바릭어", "阿瓦爾文", "阿瓦尔语", "Avaari", "Avariska", "Avarisk", "Awarski", "Avar dili", "الأوارية", "Avarština", "Avar", "Αβαρικά", "Avară", "อาวาร์", "Tiếng Avaric", "Avar", "Аварська"}},
    {"ae ave", {"Avestisk", "Avestan", "Avéstico", "Avestique", "Avestisch", "Avéstico", "Avestan", "アヴェスタ語", "Avestisch", "Авестийский", "아베스타어", "阿維斯塔文", "阿维斯塔语", "Avesta", "Avestiska", "Avestan", "Awestyjski", "Avestçe", "الأفستية", "Avestánština", "Avesztán", "Αβεστάν", "Avestană", "อเวสตะ", "Tiếng Avestan", "Avesta", "Авестійська"}},
    {"ay aym", {"Aymara", "Aymara", "Aimara", "Aymara", "Aymara", "Aimará", "Aymara", "アイマラ語", "Aymara", "Аймара", "아이마라어", "艾馬拉文", "艾马拉语", "Aimara", "Aymara", "Aymara", "Ajmara", "Aymara", "الأيمارا", "Ajmarština", "Ajmara", "Αϊμάρα", "Aymara", "ไอย์มารา", "Tiếng Aymara", "Aymara", "Аймара"}},
    {"az aze", {"Aserbajdsjansk", "Azerbaijani", "Azerbaiyano", "Azerbaïdjanais", "Aserbaidschanisch", "Azerbaijano", "Azerbaigiano", "アゼルバイジャン語", "Azerbeidzjaans", "Азербайджанский", "아제르바이잔어", "亞塞拜然文", "阿塞拜疆语", "Azeri", "Azerbajdzjanska", "Aserbajdsjansk", "Azerbejdżański", "Azerbaycan dili", "الأذربيجانية", "Ázerbájdžánština", "Azerbajdzsáni", "Αζερμπαϊτζανικά", "Azeră", "อาเซอร์ไบจาน", "Tiếng Azerbaijan", "Azerbaijani", "Азербайджанська"}},
    {"ba bak", {"Basjkirsk", "Bashkir", "Baskir", "Bachkir", "Baschkirisch", "Bashkir", "Baschiro", "バシキール語", "Basjkiers", "Башкирский", "바슈키르어", "巴什喀爾文", "巴什基尔语", "Baškiiri", "Basjkiriska", "Bashkir", "Baszkirski", "Başkırtça", "الباشكيرية", "Baškirština", "Baskír", "Μπασκίρ", "Bașkiră", "บัชคีร์", "Tiếng Bashkir", "Bashkir", "Башкирська"}},
    {"bm bam", {"Bambara", "Bambara", "Bambara", "Bambara", "Bambara", "Bambara", "Bambara", "バンバラ語", "Bambara", "Бамбара", "밤바라어", "班巴拉文", "班巴拉语", "Bambara", "Bambara", "Bambara", "Bambara", "Bambara", "البامبارا", "Bambarština", "Bambara", "Μπαμπάρα", "Bambara", "บัมบารา", "Tiếng Bambara", "Bambara", "Бамбара"}},
    {"be bel", {"Belarusisk", "Belarusian", "Bielorruso", "Biélorusse", "Belarussisch", "Bielorrusso", "Bielorusso", "ベラルーシ語", "Belarussisch", "Белорусский", "벨라루스어", "白俄羅斯文", "白俄罗斯语", "Valkovenäjä", "Belarusiska", "Belarusisk", "Białoruski", "Belarusça", "البيلاروسية", "Běloruština", "Belarusz", "Λευκορωσικά", "Belarusă", "เบลารุส", "Tiếng Belarus", "Belarusia", "Білоруська"}},
    {"bn ben", {"Bengali", "Bangla", "Bengalí", "Bengali", "Bengalisch", "Bengali", "Bengalese", "ベンガル語", "Bengaals", "Бенгальский", "벵골어", "孟加拉文", "孟加拉语", "Bengali", "Bengali", "Bengali", "Bengalski", "Bengalce", "البنغالية", "Bengálština", "Bangla", "Βεγγαλικά", "Bengaleză", "บังกลา", "Tiếng Bangla", "Bengali", "Бенгальська"}},
    {"bi bis", {"Bislama", "Bislama", "Bislama", "Bichelamar", "Bislama", "Bislamá", "Bislama", "ビスラマ語", "Bislama", "Бислама", "비슬라마어", "比斯拉馬文", "比斯拉马语", "Bislama", "Bislama", "Bislama", "Bislama", "Bislama", "البيسلامية", "Bislamština", "Bislama", "Μπισλάμα", "Bislama", "บิสลามา", "Tiếng Bislama", "Bislama", "Біслама"}},
    {"bo bod tib", {"Tibetansk", "Tibetan", "Tibetano", "Tibétain", "Tibetisch", "Tibetano", "Tibetano", "チベット語", "Tibetaans", "Тибетский", "티베트어", "藏文", "藏语", "Tiibet", "Tibetanska", "Tibetansk", "Tybetański", "Tibetçe", "التبتية", "Tibetština", "Tibeti", "Θιβετιανά", "Tibetană", "ทิเบต", "Tiếng Tây Tạng", "Tibet", "Тибетська"}},
    {"bs bos", {"Bosnisk", "Bosnian", "Bosnio", "Bosniaque", "Bosnisch", "Bósnio", "Bosniaco", "ボスニア語", "Bosnisch", "Боснийский", "보스니아어", "波士尼亞文", "波斯尼亚语", "Bosnia", "Bosniska", "Bosnisk", "Bośniacki", "Boşnakça", "البوسنية", "Bosenština", "Bosnyák", "Βοσνιακά", "Bosniacă", "บอสเนีย", "Tiếng Bosnia", "Bosnia", "Боснійська"}},
    {"br bre", {"Bretonsk", "Breton", "Bretón", "Breton", "Bretonisch", "Bretão", "Bretone", "ブルトン語", "Bretons", "Бретонский", "브르타뉴어", "布列塔尼文", "布列塔尼语", "Bretoni", "Bretonska", "Bretonsk", "Bretoński", "Bretonca", "البريتونية", "Bretonština", "Breton", "Βρετονικά", "Bretonă", "เบรตัน", "Tiếng Breton", "Breton", "Бретонська"}},
    {"bg bul", {"Bulgarsk", "Bulgarian", "Búlgaro", "Bulgare", "Bulgarisch", "Búlgaro", "Bulgaro", "ブルガリア語", "Bulgaars", "Болгарский", "불가리아어", "保加利亞文", "保加利亚语", "Bulgaria", "Bulgariska", "Bulgarsk", "Bułgarski", "Bulgarca", "البلغارية", "Bulharština", "Bolgár", "Βουλγαρικά", "Bulgară", "บัลแกเรีย", "Tiếng Bulgaria", "Bulgaria", "Болгарська"}},
    {"ca cat", {"Katalansk", "Catalan", "Catalán", "Catalan", "Katalanisch", "Catalão", "Catalano", "カタロニア語", "Catalaans", "Каталанский", "카탈로니아어", "加泰蘭文", "加泰罗尼亚语", "Katalaani", "Katalanska", "Catalansk", "Kataloński", "Katalanca", "الكتالانية", "Katalánština", "Katalán", "Καταλανικά", "Catalană", "คาตาลัน", "Tiếng Catalan", "Katalan", "Каталонська"}},
    {"cs ces cze", {"Tsjekkisk", "Czech", "Checo", "Tchèque", "Tschechisch", "Tcheco", "Ceco", "チェコ語", "Tsjechisch", "Чешский", "체코어", "捷克文", "捷克语", "Tšekki", "Tjeckiska", "Tjekkisk", "Czeski", "Çekçe", "التشيكية", "Čeština", "Cseh", "Τσεχικά", "Cehă", "เช็ก", "Tiếng Séc", "Ceko", "Чеська"}},
    {"ch cha", {"Chamorro", "Chamorro", "Chamorro", "Chamorro", "Chamorro", "Chamorro", "Chamorro", "チャモロ語", "Chamorro", "Чаморро", "차모로어", "查莫洛文", "查莫罗语", "Tšamorro", "Chamorro", "Chamorro", "Czamorro", "Çamorro dili", "التشامورو", "Čamoro", "Csamoró", "Τσαμόρο", "Chamorro", "ชามอร์โร", "Tiếng Chamorro", "Chamorro", "Чаморро"}},
    {"ce che", {"Tsjetsjensk", "Chechen", "Checheno", "Tchétchène", "Tschetschenisch", "Checheno", "Ceceno", "チェチェン語", "Tsjetsjeens", "Чеченский", "체첸어", "車臣文", "车臣语", "Tšetšeeni", "Tjetjenska", "Tjetjensk", "Czeczeński", "Çeçence", "الشيشانية", "Čečenština", "Csecsen", "Τσετσενικά", "Cecenă", "เชเชน", "Tiếng Chechen", "Chechen", "Чеченська"}},
    {"cu chu", {"Kirkeslavisk", "Church Slavic", "Eslavo eclesiástico", "Slavon d’église", "Kirchenslawisch", "Eslavo eclesiástico", "Slavo ecclesiastico", "教会スラブ語", "Kerkslavisch", "Церковнославянский", "교회 슬라브어", "宗教斯拉夫文", "教会斯拉夫语", "Kirkkoslaavi", "Kyrkslaviska", "Kirkeslavisk", "Cerkiewnosłowiański", "Kilise Slavcası", "سلافية كنسية", "Staroslověnština", "Egyházi szláv", "Εκκλησιαστικά Σλαβικά", "Slavonă", "เชอร์ชสลาวิก", "Tiếng Slavơ Nhà thờ", "Bahasa Gereja Slavonia", "Церковнословʼянська"}},
    {"cv chv", {"Tsjuvasjisk", "Chuvash", "Chuvasio", "Tchouvache", "Tschuwaschisch", "Tchuvache", "Ciuvascio", "チュヴァシ語", "Tsjoevasjisch", "Чувашский", "추바시어", "楚瓦什文", "楚瓦什语", "Tšuvassi", "Tjuvasjiska", "Tjuvasjisk", "Czuwaski", "Çuvaşça", "التشوفاشي", "Čuvaština", "Csuvas", "Τσουβασικά", "Ciuvașă", "ชูวัช", "Tiếng Chuvash", "Chuvash", "Чуваська"}},
    {"kw cor", {"Kornisk", "Cornish", "Córnico", "Cornique", "Kornisch", "Córnico", "Cornico", "コーンウォール語", "Cornish", "Корнский", "콘월어", "康瓦耳文", "康沃尔语", "Korni", "Korniska", "Cornisk", "Kornijski", "Kernevekçe", "الكورنية", "Kornština", "Korni", "Κορνουαλικά", "Cornică", "คอร์นิช", "Tiếng Cornwall", "Kornish", "Корнська"}},
    {"co cos", {"Korsikansk", "Corsican", "Corso", "Corse", "Korsisch", "Corso", "Corso", "コルシカ語", "Corsicaans", "Корсиканский", "코르시카어", "科西嘉文", "科西嘉语", "Korsika", "Korsikanska", "Korsikansk", "Korsykański", "Korsikaca", "الكورسيكية", "Korsičtina", "Korzikai", "Κορσικανικά", "Corsicană", "คอร์ซิกา", "Tiếng Corsica", "Korsika", "Корсиканська"}},
    {"cr cre", {"Cree", "Cree", "Cree", "Cree", "Cree", "Cree", "Cree", "クリー語", "Cree", "Кри", "크리어", "克里文", "克里语", "Cree", "Cree", "Cree", "Kri", "Krice", "الكرى", "Kríjština", "Krí", "Κρι", "Cree", "ครี", "Tiếng Cree", "Kree", "Крі"}},
    {"cy cym wel", {"Walisisk", "Welsh", "Galés", "Gallois", "Walisisch", "Galês", "Gallese", "ウェールズ語", "Welsh", "Валлийский", "웨일스어", "威爾斯文", "威尔士语", "Kymri", "Walesiska", "Walisisk", "Walijski", "Galce", "الويلزية", "Velština", "Walesi", "Ουαλικά", "Galeză", "เวลส์", "Tiếng Wales", "Welsh", "Валлійська"}},
    {"da dan", {"Dansk", "Danish", "Danés", "Danois", "Dänisch", "Dinamarquês", "Danese", "デンマーク語", "Deens", "Датский", "덴마크어", "丹麥文", "丹麦语", "Tanska", "Danska", "Dansk", "Duński", "Danca", "الدانمركية", "Dánština", "Dán", "Δανικά", "Daneză", "เดนมาร์ก", "Tiếng Đan Mạch", "Dansk", "Данська"}},
    {"de deu ger", {"Tysk", "German", "Alemán", "Allemand", "Deutsch", "Alemão", "Tedesco", "ドイツ語", "Duits", "Немецкий", "독일어", "德文", "德语", "Saksa", "Tyska", "Tysk", "Niemiecki", "Almanca", "الألمانية", "Němčina", "Német", "Γερμανικά", "Germană", "เยอรมัน", "Tiếng Đức", "Jerman", "Німецька"}},
    {"dv div", {"Divehi", "Divehi", "Divehi", "Maldivien", "Dhivehi", "Divehi", "Divehi", "ディベヒ語", "Divehi", "Мальдивский", "디베히어", "迪維西文", "迪维希语", "Divehi", "Divehi", "Divehi", "Malediwski", "Divehi dili", "المالديفية", "Maledivština", "Divehi", "Ντιβέχι", "Divehi", "ธิเวหิ", "Tiếng Divehi", "Divehi", "Дивехі"}},
    {"dz dzo", {"Dzongkha", "Dzongkha", "Dzongkha", "Dzongkha", "Dzongkha", "Dzonga", "Dzongkha", "ゾンカ語", "Dzongkha", "Дзонг-кэ", "종카어", "宗卡文", "宗卡语", "Dzongkha", "Dzongkha", "Dzongkha", "Dzongkha", "Dzongkha", "دزونكا", "Dzongkä", "Dzsonga", "Ντζόνγκχα", "Dzongkha", "ซองคา", "Tiếng Dzongkha", "Dzongkha", "Дзонг-ке"}},
    {"el ell gre", {"Gresk", "Greek", "Griego", "Grec", "Griechisch", "Grego", "Greco", "ギリシャ語", "Grieks", "Греческий", "그리스어", "希臘文", "希腊语", "Kreikka", "Grekiska", "Græsk", "Grecki", "Yunanca", "اليونانية", "Řečtina", "Görög", "Ελληνικά", "Greacă", "กรีก", "Tiếng Hy Lạp", "Yunani", "Грецька"}},
    {"en eng", {"Engelsk", "English", "Inglés", "Anglais", "Englisch", "Inglês", "Inglese", "英語", "Engels", "Английский", "영어", "英文", "英语", "Englanti", "Engelska", "Engelsk", "Angielski", "İngilizce", "الإنجليزية", "Angličtina", "Angol", "Αγγλικά", "Engleză", "อังกฤษ", "Tiếng Anh", "Inggris", "Англійська"}},
    {"eo epo", {"Esperanto", "Esperanto", "Esperanto", "Espéranto", "Esperanto", "Esperanto", "Esperanto", "エスペラント語", "Esperanto", "Эсперанто", "에스페란토어", "世界文", "世界语", "Esperanto", "Esperanto", "Esperanto", "Esperanto", "Esperanto", "الإسبرانتو", "Esperanto", "Eszperantó", "Εσπεράντο", "Esperanto", "เอสเปรันโต", "Tiếng Quốc Tế Ngữ", "Esperanto", "Есперанто"}},
    {"et est", {"Estisk", "Estonian", "Estonio", "Estonien", "Estnisch", "Estoniano", "Estone", "エストニア語", "Estisch", "Эстонский", "에스토니아어", "愛沙尼亞文", "爱沙尼亚语", "Viro", "Estniska", "Estisk", "Estoński", "Estonca", "الإستونية", "Estonština", "Észt", "Εσθονικά", "Estonă", "เอสโตเนีย", "Tiếng Estonia", "Estonia", "Естонська"}},
    {"eu eus baq", {"Baskisk", "Basque", "Euskera", "Basque", "Baskisch", "Basco", "Basco", "バスク語", "Baskisch", "Баскский", "바스크어", "巴斯克文", "巴斯克语", "Baski", "Baskiska", "Baskisk", "Baskijski", "Baskça", "الباسكية", "Baskičtina", "Baszk", "Βασκικά", "Bască", "บาสก์", "Tiếng Basque", "Basque", "Баскська"}},
    {"ee ewe", {"Ewe", "Ewe", "Ewé", "Éwé", "Ewe", "Ewe", "Ewe", "エウェ語", "Ewe", "Эве", "에웨어", "埃維文", "埃维语", "Ewe", "Ewe", "Ewe", "Ewe", "Ewe", "الإيوي", "Eweština", "Eve", "Έουε", "Ewe", "เอเว", "Tiếng Ewe", "Ewe", "Еве"}},
    {"fo fao", {"Færøysk", "Faroese", "Feroés", "Féroïen", "Färöisch", "Feroês", "Faroese", "フェロー語", "Faeröers", "Фарерский", "페로어", "法羅文", "法罗语", "Fääri", "Färöiska", "Færøsk", "Farerski", "Faroe dili", "الفاروية", "Faerština", "Feröeri", "Φεροϊκά", "Feroeză", "แฟโร", "Tiếng Faroe", "Faroe", "Фарерська"}},
    {"fa fas per", {"Persisk", "Persian", "Persa", "Persan", "Persisch", "Persa", "Persiano", "ペルシア語", "Perzisch", "Персидский", "페르시아어", "波斯文", "波斯语", "Persia", "Persiska", "Persisk", "Perski", "Farsça", "الفارسية", "Perština", "Perzsa", "Περσικά", "Persană", "เปอร์เซีย", "Tiếng Ba Tư", "Persia", "Перська"}},
    {"fj fij", {"Fijiansk", "Fijian", "Fiyiano", "Fidjien", "Fidschi", "Fijiano", "Figiano", "フィジー語", "Fijisch", "Фиджи", "피지어", "斐濟文", "斐济语", "Fidži", "Fijianska", "Fijiansk", "Fidżijski", "Fiji dili", "الفيجية", "Fidžijština", "Fidzsi", "Φίτζι", "Fijiană", "ฟิจิ", "Tiếng Fiji", "Fiji", "Фіджі"}},
    {"fi fin", {"Finsk", "Finnish", "Finés", "Finnois", "Finnisch", "Finlandês", "Finlandese", "フィンランド語", "Fins", "Финский", "핀란드어", "芬蘭文", "芬兰语", "Suomi", "Finska", "Finsk", "Fiński", "Fince", "الفنلندية", "Finština", "Finn", "Φινλανδικά", "Finlandeză", "ฟินแลนด์", "Tiếng Phần Lan", "Suomi", "Фінська"}},
    {"fr fra fre", {"Fransk", "French", "Francés", "Français", "Französisch", "Francês", "Francese", "フランス語", "Frans", "Французский", "프랑스어", "法文", "法语", "Ranska", "Franska", "Fransk", "Francuski", "Fransızca", "الفرنسية", "Francouzština", "Francia", "Γαλλικά", "Franceză", "ฝรั่งเศส", "Tiếng Pháp", "Prancis", "Французька"}},
    {"fy fry", {"Vestfrisisk", "Western Frisian", "Frisón occidental", "Frison occidental", "Westfriesisch", "Frísio ocidental", "Frisone occidentale", "西フリジア語", "Fries", "Западнофризский", "서부 프리지아어", "西弗里西亞文", "西弗里西亚语", "Länsifriisi", "Västfrisiska", "Vestfrisisk", "Zachodniofryzyjski", "Batı Frizcesi", "الفريزيان", "Fríština (západní)", "Nyugati fríz", "Δυτικά Φριζικά", "Frizonă occidentală", "ฟริเซียนตะวันตก", "Tiếng Frisia", "Frisia Barat", "Західнофризька"}},
    {"ff ful", {"Fulfulde", "Fula", "Fula", "Peul", "Ful", "Fula", "Fulah", "フラ語", "Fulah", "Фулах", "풀라어", "富拉文", "富拉语", "Fulani", "Fulani", "Fulah", "Fulani", "Fula dili", "الفولانية", "Fulbština", "Fulani", "Φουλά", "Fulah", "ฟูลาห์", "Tiếng Fulah", "Fula", "Фула"}},
    {"gd gla", {"Skotsk-gælisk", "Scottish Gaelic", "Gaélico escocés", "Gaélique écossais", "Gälisch (Schottland)", "Gaélico escocês", "Gaelico scozzese", "スコットランド・ゲール語", "Schots-Gaelisch", "Гэльский", "스코틀랜드 게일어", "蘇格蘭蓋爾文", "苏格兰盖尔语", "Gaeli", "Skotsk gaeliska", "Skotsk gælisk", "Szkocki gaelicki", "İskoç Gaelcesi", "الغيلية الأسكتلندية", "Skotská gaelština", "Skóciai kelta", "Σκωτικά Κελτικά", "Gaelică scoțiană", "เกลิกสกอต", "Tiếng Gael Scotland", "Gaelik Skotlandia", "Шотландська гельська"}},
    {"ga gle", {"Irsk", "Irish", "Irlandés", "Irlandais", "Irisch", "Irlandês", "Irlandese", "アイルランド語", "Iers", "Ирландский", "아일랜드어", "愛爾蘭文", "爱尔兰语", "Iiri", "Iriska", "Irsk", "Irlandzki", "İrlandaca", "الأيرلندية", "Irština", "Ír", "Ιρλανδικά", "Irlandeză", "ไอริช", "Tiếng Ireland", "Irlandia", "Ірландська"}},
    {"gl glg", {"Galisisk", "Galician", "Gallego", "Galicien", "Galicisch", "Galego", "Galiziano", "ガリシア語", "Galicisch", "Галисийский", "갈리시아어", "加利西亞文", "加利西亚语", "Galicia", "Galiciska", "Galicisk", "Galicyjski", "Galiçyaca", "الجاليكية", "Galicijština", "Gallego", "Γαλικιανά", "Galiciană", "กาลิเซีย", "Tiếng Galician", "Galisia", "Галісійська"}},
    {"gv glv", {"Mansk", "Manx", "Manés", "Mannois", "Manx", "Manx", "Mannese", "マン島語", "Manx", "Мэнский", "맹크스어", "曼島文", "马恩语", "Manksi", "Manx", "Manx", "Manx", "Man dili", "المنكية", "Manština", "Man-szigeti", "Μανξ", "Manx", "มานซ์", "Tiếng Manx", "Manx", "Менкська"}},
    {"gn grn", {"Guarani", "Guarani", "Guaraní", "Guarani", "Guaraní", "Guarani", "Guaraní", "グアラニー語", "Guaraní", "Гуарани", "과라니어", "瓜拉尼文", "瓜拉尼语", "Guarani", "Guaraní", "Guarani", "Guarani", "Guarani dili", "الغوارانية", "Guaranština", "Guarani", "Γκουαρανί", "Guarani", "กัวรานี", "Tiếng Guarani", "Guarani", "Гуарані"}},
    {"gu guj", {"Gujarati", "Gujarati", "Guyaratí", "Goudjarati", "Gujarati", "Guzerate", "Gujarati", "グジャラート語", "Gujarati", "Гуджарати", "구자라트어", "古吉拉特文", "古吉拉特语", "Gudžarati", "Gujarati", "Gujarati", "Gudżarati", "Güceratça", "الغوجاراتية", "Gudžarátština", "Gudzsaráti", "Γκουτζαρατικά", "Gujarati", "คุชราต", "Tiếng Gujarati", "Gujarat", "Гуджараті"}},
    {"ht hat", {"Haitisk", "Haitian Creole", "Criollo haitiano", "Créole haïtien", "Haiti-Kreolisch", "Haitiano", "Creolo haitiano", "ハイチ・クレオール語", "Haïtiaans Creools", "Гаитянский", "아이티어", "海地文", "海地克里奥尔语", "Haiti", "Haitiska", "Haitisk", "Kreolski haitański", "Haiti Kreyolu", "الكريولية الهايتية", "Haitština", "Haiti kreol", "Αϊτιανά", "Haitiană", "เฮติครีโอล", "Tiếng Haiti", "Kreol Haiti", "Гаїтянська креольська"}},
    {"ha hau", {"Hausa", "Hausa", "Hausa", "Haoussa", "Haussa", "Hauçá", "Hausa", "ハウサ語", "Hausa", "Хауса", "하우사어", "豪薩文", "豪萨语", "Hausa", "Hausa", "Hausa", "Hausa", "Hausa dili", "الهوسا", "Hauština", "Hausza", "Χάουσα", "Hausa", "เฮาซา", "Tiếng Hausa", "Hausa", "Хауса"}},
    {"sh hbs", {"Serbokroatisk", "Serbo-Croatian", "Serbocroata", "Serbo-croate", "Serbo-Kroatisch", "Servo-croata", "Serbo-croato", "セルボ・クロアチア語", "Servo-Kroatisch", "Сербскохорватский", "세르비아-크로아티아어", "塞爾維亞克羅埃西亞文", "塞尔维亚-克罗地亚语", "Serbokroaatti", "Serbokroatiska", "Serbokroatisk", "Serbsko-chorwacki", "Sırp-Hırvat Dili", "صربية-كرواتية", "Srbochorvatština", "Szerbhorvát", "Σερβοκροατικά", "Sârbo-croată", "เซอร์โบ-โครเอเชีย", "Tiếng Serbo-Croatia", "Serbo-Kroasia", "Сербсько-хорватська"}},
    {"he heb", {"Hebraisk", "Hebrew", "Hebreo", "Hébreu", "Hebräisch", "Hebraico", "Ebraico", "ヘブライ語", "Hebreeuws", "Иврит", "히브리어", "希伯來文", "希伯来语", "Heprea", "Hebreiska", "Hebraisk", "Hebrajski", "İbranice", "العبرية", "Hebrejština", "Héber", "Εβραϊκά", "Ebraică", "ฮิบรู", "Tiếng Do Thái", "Ibrani", "Іврит"}},
    {"hz her", {"Herero", "Herero", "Herero", "Héréro", "Herero", "Herero", "Herero", "ヘレロ語", "Herero", "Гереро", "헤레로어", "赫雷羅文", "赫雷罗语", "Herero", "Herero", "Herero", "Herero", "Herero dili", "الهيريرو", "Hererština", "Herero", "Χερέρο", "Herero", "เฮเรโร", "Tiếng Herero", "Herero", "Гереро"}},
    {"hi hin", {"Hindi", "Hindi", "Hindi", "Hindi", "Hindi", "Híndi", "Hindi", "ヒンディー語", "Hindi", "Хинди", "힌디어", "印地文", "印地语", "Hindi", "Hindi", "Hindi", "Hindi", "Hintçe", "الهندية", "Hindština", "Hindi", "Χίντι", "Hindi", "ฮินดี", "Tiếng Hindi", "Hindi", "Гінді"}},
    {"ho hmo", {"Hiri motu", "Hiri Motu", "Hiri motu", "Hiri motu", "Hiri-Motu", "Hiri motu", "Hiri motu", "ヒリモツ語", "Hiri Motu", "Хиримоту", "히리 모투어", "西里莫圖土文", "希里莫图语", "Hiri-motu", "Hirimotu", "Hirimotu", "Hiri motu", "Hiri Motu", "الهيري موتو", "Hiri motu", "Hiri motu", "Χίρι Μότου", "Hiri motu", "ฮีรีโมตู", "Tiếng Hiri Motu", "Hiri Motu", "Хірі-моту"}},
    {"hr hrv", {"Kroatisk", "Croatian", "Croata", "Croate", "Kroatisch", "Croata", "Croato", "クロアチア語", "Kroatisch", "Хорватский", "크로아티아어", "克羅埃西亞文", "克罗地亚语", "Kroatia", "Kroatiska", "Kroatisk", "Chorwacki", "Hırvatça", "الكرواتية", "Chorvatština", "Horvát", "Κροατικά", "Croată", "โครเอเชีย", "Tiếng Croatia", "Kroasia", "Хорватська"}},
    {"hu hun", {"Ungarsk", "Hungarian", "Húngaro", "Hongrois", "Ungarisch", "Húngaro", "Ungherese", "ハンガリー語", "Hongaars", "Венгерский", "헝가리어", "匈牙利文", "匈牙利语", "Unkari", "Ungerska", "Ungarsk", "Węgierski", "Macarca", "الهنغارية", "Maďarština", "Magyar", "Ουγγρικά", "Maghiară", "ฮังการี", "Tiếng Hungary", "Hungaria", "Угорська"}},
    {"hy hye arm", {"Armensk", "Armenian", "Armenio", "Arménien", "Armenisch", "Armênio", "Armeno", "アルメニア語", "Armeens", "Армянский", "아르메니아어", "亞美尼亞文", "亚美尼亚语", "Armenia", "Armeniska", "Armensk", "Ormiański", "Ermenice", "الأرمنية", "Arménština", "Örmény", "Αρμενικά", "Armeană", "อาร์เมเนีย", "Tiếng Armenia", "Armenia", "Вірменська"}},
    {"ig ibo", {"Ibo", "Igbo", "Igbo", "Igbo", "Igbo", "Igbo", "Igbo", "イボ語", "Igbo", "Игбо", "이그보어", "伊布文", "伊博语", "Igbo", "Igbo", "Igbo", "Igbo", "İbo dili", "الإيجبو", "Igboština", "Igbó", "Ίγκμπο", "Igbo", "อิกโบ", "Tiếng Igbo", "Igbo", "Ігбо"}},
    {"io ido", {"Ido", "Ido", "Ido", "Ido", "Ido", "Ido", "Ido", "イド語", "Ido", "Идо", "이도어", "伊多文", "伊多语", "Ido", "Ido", "Ido", "Ido", "Ido", "الإيدو", "Ido", "Idó", "Ίντο", "Ido", "อีโด", "Tiếng Ido", "Ido", "Ідо"}},
    {"ii iii", {"Sichuan-yi", "Sichuan Yi", "Yi de Sichuán", "Yi du Sichuan", "Yi", "Sichuan yi", "Sichuan yi", "四川イ語", "Yi", "Носу", "쓰촨 이어", "四川彝文", "凉山彝语", "Sichuanin-yi", "Szezuan i", "Sichuan yi", "Syczuański", "Sichuan Yi", "السيتشيون يي", "Iština (sečuánská)", "Szecsuán ji", "Σίτσουαν Γι", "Yi din Sichuan", "เสฉวนยี่", "Tiếng Di Tứ Xuyên", "Sichuan Yi", "Сичуаньська ї"}},
    {"iu iku", {"Inuktitut", "Inuktitut", "Inuktitut", "Inuktitut", "Inuktitut", "Inuktitut", "Inuktitut", "イヌクティトット語", "Inuktitut", "Инуктитут", "이눅티투트어", "因紐特文", "因纽特语", "Inuktitut", "Inuktitut", "Inuktitut", "Inuktitut", "İnuktitut dili", "الإينكتيتت", "Inuktitutština", "Inuktitut", "Ινούκτιτουτ", "Inuktitut", "อินุกติตุต", "Tiếng Inuktitut", "Inuktitut", "Інуктитут"}},
    {"ie ile", {"Interlingue", "Interlingue", "Interlingue", "Interlingue", "Interlingue", "Interlingue", "Interlingue", "インターリング", "Interlingue", "Интерлингве", "인테르링구에", "國際文（E）", "国际文字（E）", "Interlingue", "Interlingue", "Interlingue", "Interlingue", "Interlingue", "الإنترلينج", "Interlingue", "Interlingue", "Ιντερλίνγκουε", "Interlingue", "อินเตอร์ลิงกิว", "Tiếng Interlingue", "Interlingue", "Інтерлінгве"}},
    {"ia ina", {"Interlingua", "Interlingua", "Interlingua", "Interlingua", "Interlingua", "Interlíngua", "Interlingua", "インターリングア", "Interlingua", "Интерлингва", "인터링구아", "國際文", "国际语", "Interlingua", "Interlingua", "Interlingua", "Interlingua", "İnterlingua", "اللّغة الوسيطة", "Interlingua", "Interlingva", "Ιντερλίνγκουα", "Interlingua", "อินเตอร์ลิงกัว", "Tiếng Khoa Học Quốc Tế", "Interlingua", "Інтерлінгва"}},
    {"id ind", {"Indonesisk", "Indonesian", "Indonesio", "Indonésien", "Indonesisch", "Indonésio", "Indonesiano", "インドネシア語", "Indonesisch", "Индонезийский", "인도네시아어", "印尼文", "印度尼西亚语", "Indonesia", "Indonesiska", "Indonesisk", "Indonezyjski", "Endonezce", "الإندونيسية", "Indonéština", "Indonéz", "Ινδονησιακά", "Indoneziană", "อินโดนีเซีย", "Tiếng Indonesia", "Indonesia", "Індонезійська"}},
    {"ik ipk", {"Inupiak", "Inupiaq", "Inupiaq", "Inupiaq", "Inupiak", "Inupiaque", "Inupiak", "イヌピアック語", "Inupiaq", "Инупиак", "이누피아크어", "依奴皮維克文", "伊努皮克语", "Inupiaq", "Inupiak", "Inupiaq", "Inupiak", "İnyupikçe", "الإينبياك", "Inupiakština", "Inupiak", "Ινουπιάκ", "Inupiak", "อีนูเปียก", "Tiếng Inupiaq", "Inupiak", "Інупіак"}},
    {"is isl ice", {"Islandsk", "Icelandic", "Islandés", "Islandais", "Isländisch", "Islandês", "Islandese", "アイスランド語", "IJslands", "Исландский", "아이슬란드어", "冰島文", "冰岛语", "Islanti", "Isländska", "Islandsk", "Islandzki", "İzlandaca", "الأيسلندية", "Islandština", "Izlandi", "Ισλανδικά", "Islandeză", "ไอซ์แลนด์", "Tiếng Iceland", "Islandia", "Ісландська"}},
    {"it ita", {"Italiensk", "Italian", "Italiano", "Italien", "Italienisch", "Italiano", "Italiano", "イタリア語", "Italiaans", "Итальянский", "이탈리아어", "義大利文", "意大利语", "Italia", "Italienska", "Italiensk", "Włoski", "İtalyanca", "الإيطالية", "Italština", "Olasz", "Ιταλικά", "Italiană", "อิตาลี", "Tiếng Italy", "Italia", "Італійська"}},
    {"jv jav", {"Javanesisk", "Javanese", "Javanés", "Javanais", "Javanisch", "Javanês", "Giavanese", "ジャワ語", "Javaans", "Яванский", "자바어", "爪哇文", "爪哇语", "Jaava", "Javanesiska", "Javanesisk", "Jawajski", "Cava dili", "الجاوية", "Javánština", "Jávai", "Ιαβανικά", "Javaneză", "ชวา", "Tiếng Java", "Jawa", "Яванська"}},
    {"ja jpn", {"Japansk", "Japanese", "Japonés", "Japonais", "Japanisch", "Japonês", "Giapponese", "日本語", "Japans", "Японский", "일본어", "日文", "日语", "Japani", "Japanska", "Japansk", "Japoński", "Japonca", "اليابانية", "Japonština", "Japán", "Ιαπωνικά", "Japoneză", "ญี่ปุ่น", "Tiếng Nhật", "Jepang", "Японська"}},
    {"kl kal", {"Grønlandsk", "Kalaallisut", "Groenlandés", "Groenlandais", "Grönländisch", "Groenlandês", "Groenlandese", "グリーンランド語", "Groenlands", "Гренландский", "그린란드어", "格陵蘭文", "格陵兰语", "Kalaallisut", "Grönländska", "Grønlandsk", "Grenlandzki", "Grönland dili", "الكالاليست", "Grónština", "Grönlandi", "Καλαάλισουτ", "Kalaallisut", "กรีนแลนด์", "Tiếng Kalaallisut", "Kalaallisut", "Калааллісут"}},
    {"kn kan", {"Kannada", "Kannada", "Canarés", "Kannada", "Kannada", "Canarim", "Kannada", "カンナダ語", "Kannada", "Каннада", "칸나다어", "坎那達文", "卡纳达语", "Kannada", "Kannada", "Kannada", "Kannada", "Kannada dili", "الكانادا", "Kannadština", "Kannada", "Κανάντα", "Kannada", "กันนาดา", "Tiếng Kannada", "Kannada", "Каннада"}},
    {"ks kas", {"Kasjmiri", "Kashmiri", "Cachemir", "Cachemiri", "Kaschmiri", "Caxemira", "Kashmiri", "カシミール語", "Kasjmiri", "Кашмири", "카슈미르어", "喀什米爾文", "克什米尔语", "Kašmiri", "Kashmiriska", "Kashmiri", "Kaszmirski", "Keşmir dili", "الكشميرية", "Kašmírština", "Kasmíri", "Κασμιρικά", "Cașmiră", "แคชเมียร์", "Tiếng Kashmir", "Kashmir", "Кашмірська"}},
    {"ka kat geo", {"Georgisk", "Georgian", "Georgiano", "Géorgien", "Georgisch", "Georgiano", "Georgiano", "ジョージア語", "Georgisch", "Грузинский", "조지아어", "喬治亞文", "格鲁吉亚语", "Georgia", "Georgiska", "Georgisk", "Gruziński", "Gürcüce", "الجورجية", "Gruzínština", "Grúz", "Γεωργιανά", "Georgiană", "จอร์เจีย", "Tiếng Georgia", "Georgia", "Грузинська"}},
    {"kr kau", {"Kanuri", "Kanuri", "Kanuri", "Kanouri", "Kanuri", "Canúri", "Kanuri", "カヌリ語", "Kanuri", "Канури", "칸누리어", "卡努里文", "卡努里语", "Kanuri", "Kanuri", "Kanuri", "Kanuri", "Kanuri dili", "الكانوري", "Kanuri", "Kanuri", "Κανούρι", "Kanuri", "คานูรี", "Tiếng Kanuri", "Kanuri", "Канурі"}},
    {"kk kaz", {"Kasakhisk", "Kazakh", "Kazajo", "Kazakh", "Kasachisch", "Cazaque", "Kazako", "カザフ語", "Kazachs", "Казахский", "카자흐어", "哈薩克文", "哈萨克语", "Kazakki", "Kazakiska", "Kasakhisk", "Kazachski", "Kazakça", "الكازاخستانية", "Kazaština", "Kazah", "Καζακικά", "Kazahă", "คาซัค", "Tiếng Kazakh", "Kazakh", "Казахська"}},
    {"km khm", {"Khmer", "Khmer", "Jemer", "Khmer", "Khmer", "Khmer", "Khmer", "クメール語", "Khmer", "Кхмерский", "크메르어", "高棉文", "高棉语", "Khmer", "Kambodjanska", "Khmer", "Khmerski", "Khmer dili", "الخميرية", "Khmérština", "Khmer", "Χμερ", "Khmeră", "เขมร", "Tiếng Khmer", "Khmer", "Кхмерська"}},
    {"ki kik", {"Kikuyu", "Kikuyu", "Kikuyu", "Kikuyu", "Kikuyu", "Quicuio", "Kikuyu", "キクユ語", "Gikuyu", "Кикуйю", "키쿠유어", "吉庫尤文", "吉库尤语", "Kikuju", "Kikuyu", "Kikuyu", "Kikuju", "Kikuyu", "الكيكيو", "Kikujština", "Kikuju", "Κικούγιου", "Kikuyu", "กีกูยู", "Tiếng Kikuyu", "Kikuyu", "Кікуйю"}},
    {"rw kin", {"Kinyarwanda", "Kinyarwanda", "Kinyarwanda", "Kinyarwanda", "Kinyarwanda", "Quiniaruanda", "Kinyarwanda", "キニアルワンダ語", "Kinyarwanda", "Киньяруанда", "르완다어", "盧安達文", "卢旺达语", "Ruanda", "Kinjarwanda", "Kinyarwanda", "Kinya-ruanda", "Kinyarwanda", "الكينيارواندا", "Kiňarwandština", "Kinyarvanda", "Κινιαρουάντα", "Kinyarwanda", "รวันดา", "Tiếng Kinyarwanda", "Kinyarwanda", "Кіньяруанда"}},
    {"ky kir", {"Kirgisisk", "Kyrgyz", "Kirguís", "Kirghize", "Kirgisisch", "Quirguiz", "Kirghiso", "キルギス語", "Kirgizisch", "Киргизский", "키르기스어", "吉爾吉斯文", "柯尔克孜语", "Kirgiisi", "Kirgiziska", "Kirgisisk", "Kirgiski", "Kırgızca", "القيرغيزية", "Kyrgyzština", "Kirgiz", "Κιργιζικά", "Kârgâză", "คีร์กีซ", "Tiếng Kyrgyz", "Kirgiz", "Киргизька"}},
    {"kv kom", {"Komi", "Komi", "Komi", "Komi", "Komi", "Komi", "Komi", "コミ語", "Komi", "Коми", "코미어", "科米文", "科米语", "Komi", "Kome", "Komi", "Komi", "Komi", "الكومي", "Komijština", "Komi", "Κόμι", "Komi", "โกมิ", "Tiếng Komi", "Komi", "Комі"}},
    {"kg kon", {"Kikongo", "Kongo", "Kongo", "Kikongo", "Kongolesisch", "Congolês", "Kongo", "コンゴ語", "Kongo", "Конго", "콩고어", "剛果文", "刚果语", "Kongo", "Kikongo", "Kongo", "Kongo", "Kongo dili", "الكونغو", "Konžština", "Kongo", "Κονγκό", "Congoleză", "คองโก", "Tiếng Kongo", "Kongo", "Конґолезька"}},
    {"ko kor", {"Koreansk", "Korean", "Coreano", "Coréen", "Koreanisch", "Coreano", "Coreano", "韓国語", "Koreaans", "Корейский", "한국어", "韓文", "韩语", "Korea", "Koreanska", "Koreansk", "Koreański", "Korece", "الكورية", "Korejština", "Koreai", "Κορεατικά", "Coreeană", "เกาหลี", "Tiếng Hàn", "Korea", "Корейська"}},
    {"kj kua", {"Kuanyama", "Kuanyama", "Kuanyama", "Kuanyama", "Kwanyama", "Cuanhama", "Kuanyama", "クワニャマ語", "Kuanyama", "Кунама", "쿠안야마어", "廣亞馬文", "宽亚玛语", "Kuanjama", "Kuanyama", "Kuanyama", "Kwanyama", "Kuanyama", "كوانياما", "Kuaňamština", "Kuanyama", "Κουανιάμα", "Kuanyama", "กวนยามา", "Tiếng Kuanyama", "Kuanyama", "Кунама"}},
    {"ku kur", {"Kurdisk", "Kurdish", "Kurdo", "Kurde", "Kurdisch", "Curdo", "Curdo", "クルド語", "Koerdisch", "Курдский", "쿠르드어", "庫德文", "库尔德语", "Kurdi", "Kurdiska", "Kurdisk", "Kurdyjski", "Kürtçe", "الكردية", "Kurdština", "Kurd", "Κουρδικά", "Kurdă", "เคิร์ด", "Tiếng Kurd", "Kurdi", "Курдська"}},
    {"lo lao", {"Laotisk", "Lao", "Lao", "Lao", "Laotisch", "Laosiano", "Lao", "ラオ語", "Laotiaans", "Лаосский", "라오어", "寮文", "老挝语", "Lao", "Laotiska", "Lao", "Laotański", "Lao dili", "اللاوية", "Laoština", "Lao", "Λαοτινά", "Laoțiană", "ลาว", "Tiếng Lào", "Lao", "Лаоська"}},
    {"la lat", {"Latin", "Latin", "Latín", "Latin", "Latein", "Latim", "Latino", "ラテン語", "Latijn", "Латинский", "라틴어", "拉丁文", "拉丁语", "Latina", "Latin", "Latin", "Łaciński", "Latince", "اللاتينية", "Latina", "Latin", "Λατινικά", "Latină", "ละติน", "Tiếng La-tinh", "Latin", "Латинська"}},
    {"lv lav", {"Latvisk", "Latvian", "Letón", "Letton", "Lettisch", "Letão", "Lettone", "ラトビア語", "Lets", "Латышский", "라트비아어", "拉脫維亞文", "拉脱维亚语", "Latvia", "Lettiska", "Lettisk", "Łotewski", "Letonca", "اللاتفية", "Lotyština", "Lett", "Λετονικά", "Letonă", "ลัตเวีย", "Tiếng Latvia", "Latvia", "Латиська"}},
    {"li lim", {"Limburgsk", "Limburgish", "Limburgués", "Limbourgeois", "Limburgisch", "Limburguês", "Limburghese", "リンブルフ語", "Limburgs", "Лимбургский", "림버거어", "林堡文", "林堡语", "Limburg", "Limburgiska", "Limburgsk", "Limburski", "Limburgca", "الليمبورغية", "Limburština", "Limburgi", "Λιμβουργιανά", "Limburgheză", "ลิมเบิร์ก", "Tiếng Limburg", "Limburgia", "Лімбургійська"}},
    {"ln lin", {"Lingala", "Lingala", "Lingala", "Lingala", "Lingala", "Lingala", "Lingala", "リンガラ語", "Lingala", "Лингала", "링갈라어", "林加拉文", "林加拉语", "Lingala", "Lingala", "Lingala", "Lingala", "Lingala", "اللينجالا", "Lingalština", "Lingala", "Λινγκάλα", "Lingala", "ลิงกาลา", "Tiếng Lingala", "Lingala", "Лінгала"}},
    {"lt lit", {"Litauisk", "Lithuanian", "Lituano", "Lituanien", "Litauisch", "Lituano", "Lituano", "リトアニア語", "Litouws", "Литовский", "리투아니아어", "立陶宛文", "立陶宛语", "Liettua", "Litauiska", "Litauisk", "Litewski", "Litvanca", "الليتوانية", "Litevština", "Litván", "Λιθουανικά", "Lituaniană", "ลิทัวเนีย", "Tiếng Litva", "Lituania", "Литовська"}},
    {"lb ltz", {"Luxemburgsk", "Luxembourgish", "Luxemburgués", "Luxembourgeois", "Luxemburgisch", "Luxemburguês", "Lussemburghese", "ルクセンブルク語", "Luxemburgs", "Люксембургский", "룩셈부르크어", "盧森堡文", "卢森堡语", "Luxemburg", "Luxemburgiska", "Luxembourgsk", "Luksemburski", "Lüksemburgca", "اللكسمبورغية", "Lucemburština", "Luxemburgi", "Λουξεμβουργιανά", "Luxemburgheză", "ลักเซมเบิร์ก", "Tiếng Luxembourg", "Luksemburg", "Люксембурзька"}},
    {"lu lub", {"Luba-katanga", "Luba-Katanga", "Luba-katanga", "Luba-katanga (kiluba)", "Luba-Katanga", "Luba-catanga", "Luba-katanga", "ルバ・カタンガ語", "Luba-Katanga", "Луба-катанга", "루바-카탄가어", "魯巴加丹加文", "鲁巴加丹加语", "Katanganluba", "Luba-katanga", "Luba-Katanga", "Luba-katanga", "Luba-Katanga", "اللوبا كاتانغا", "Lubu-katanžština", "Luba-katanga", "Λούμπα-Κατάνγκα", "Luba-katanga", "ลูบา-กาตองกา", "Tiếng Luba-Katanga", "Luba-Katanga", "Луба-катанга"}},
    {"lg lug", {"Ganda", "Ganda", "Ganda", "Ganda", "Ganda", "Luganda", "Ganda", "ガンダ語", "Luganda", "Ганда", "간다어", "干達文", "卢干达语", "Ganda", "Luganda", "Ganda", "Ganda", "Ganda", "الغاندا", "Gandština", "Ganda", "Γκάντα", "Ganda", "ยูกันดา", "Tiếng Ganda", "Ganda", "Ганда"}},
    {"mh mah", {"Marshallesisk", "Marshallese", "Marshalés", "Marshallais", "Marschallesisch", "Marshalês", "Marshallese", "マーシャル語", "Marshallees", "Маршалльский", "마셜어", "馬紹爾文", "马绍尔语", "Marshall", "Marshalliska", "Marshallese", "Marszalski", "Marshall Adaları dili", "المارشالية", "Maršálština", "Marshalli", "Μαρσαλέζικα", "Marshalleză", "มาร์แชลล์", "Tiếng Marshall", "Marshall", "Маршалльська"}},
    {"ml mal", {"Malayalam", "Malayalam", "Malayálam", "Malayalam", "Malayalam", "Malaiala", "Malayalam", "マラヤーラム語", "Malayalam", "Малаялам", "말라얄람어", "馬來亞拉姆文", "马拉雅拉姆语", "Malajalam", "Malayalam", "Malayalam", "Malajalam", "Malayalam dili", "المالايالامية", "Malajálamština", "Malajálam", "Μαλαγιαλαμικά", "Malayalam", "มาลายาลัม", "Tiếng Malayalam", "Malayalam", "Малаялам"}},
    {"mr mar", {"Marathi", "Marathi", "Maratí", "Marathi", "Marathi", "Marati", "Marathi", "マラーティー語", "Marathi", "Маратхи", "마라티어", "馬拉地文", "马拉地语", "Marathi", "Marathi", "Marathi", "Marathi", "Marathi dili", "الماراثية", "Maráthština", "Maráthi", "Μαραθικά", "Marathi", "มราฐี", "Tiếng Marathi", "Marathi", "Маратхі"}},
    {"mk mkd mac", {"Makedonsk", "Macedonian", "Macedonio", "Macédonien", "Mazedonisch", "Macedônio", "Macedone", "マケドニア語", "Macedonisch", "Македонский", "마케도니아어", "馬其頓文", "马其顿语", "Makedonia", "Makedonska", "Makedonsk", "Macedoński", "Makedonca", "المقدونية", "Makedonština", "Macedón", "Σλαβομακεδονικά", "Macedoneană", "มาซิโดเนีย", "Tiếng Macedonia", "Makedonia", "Македонська"}},
    {"mg mlg", {"Gassisk", "Malagasy", "Malgache", "Malgache", "Malagasy", "Malgaxe", "Malgascio", "マダガスカル語", "Malagassisch", "Малагасийский", "말라가시어", "馬達加斯加文", "马拉加斯语", "Malagassi", "Malagassiska", "Malagassisk", "Malgaski", "Malgaşça", "الملغاشي", "Malgaština", "Malgas", "Μαλγασικά", "Malgașă", "มาลากาซี", "Tiếng Malagasy", "Malagasi", "Малагасійська"}},
    {"mt mlt", {"Maltesisk", "Maltese", "Maltés", "Maltais", "Maltesisch", "Maltês", "Maltese", "マルタ語", "Maltees", "Мальтийский", "몰타어", "馬爾他文", "马耳他语", "Malta", "Maltesiska", "Maltesisk", "Maltański", "Maltaca", "المالطية", "Maltština", "Máltai", "Μαλτεζικά", "Malteză", "มอลตา", "Tiếng Malta", "Malta", "Мальтійська"}},
    {"mn mon", {"Mongolsk", "Mongolian", "Mongol", "Mongol", "Mongolisch", "Mongol", "Mongolo", "モンゴル語", "Mongools", "Монгольский", "몽골어", "蒙古文", "蒙古语", "Mongoli", "Mongoliska", "Mongolsk", "Mongolski", "Moğolca", "المنغولية", "Mongolština", "Mongol", "Μογγολικά", "Mongolă", "มองโกเลีย", "Tiếng Mông Cổ", "Mongolia", "Монгольська"}},
    {"mi mri mao", {"Maori", "Māori", "Maorí", "Maori", "Māori", "Maori", "Maori", "マオリ語", "Maori", "Маори", "마오리어", "毛利文", "毛利语", "Maori", "Maori", "Maori", "Maoryjski", "Maori dili", "الماورية", "Maorština", "Maori", "Μαορί", "Maori", "เมารี", "Tiếng Māori", "Maori", "Маорі"}},
    {"ms msa may", {"Malayisk", "Malay", "Malayo", "Malais", "Malaiisch", "Malaio", "Malese", "マレー語", "Maleis", "Малайский", "말레이어", "馬來文", "马来语", "Malaiji", "Malajiska", "Malajisk", "Malajski", "Malayca", "الماليزية", "Malajština", "Maláj", "Μαλαισιανά", "Malaeză", "มาเลย์", "Tiếng Mã Lai", "Melayu", "Малайська"}},
    {"my mya bur", {"Burmesisk", "Burmese", "Birmano", "Birman", "Birmanisch", "Birmanês", "Birmano", "ミャンマー語", "Birmaans", "Бирманский", "버마어", "緬甸文", "缅甸语", "Burma", "Burmesiska", "Burmesisk", "Birmański", "Birman dili", "البورمية", "Barmština", "Burmai", "Βιρμανικά", "Birmană", "พม่า", "Tiếng Miến Điện", "Burma", "Бірманська"}},
    {"na nau", {"Nauru", "Nauru", "Nauruano", "Nauruan", "Nauruisch", "Nauruano", "Nauru", "ナウル語", "Nauruaans", "Науру", "나우루어", "諾魯文", "瑙鲁语", "Nauru", "Nauruanska", "Nauru", "Nauruański", "Nauru dili", "النورو", "Naurština", "Naurui", "Ναούρου", "Nauru", "นาอูรู", "Tiếng Nauru", "Nauru", "Науру"}},
    {"nv nav", {"Navajo", "Navajo", "Navajo", "Navajo", "Navajo", "Navajo", "Navajo", "ナバホ語", "Navajo", "Навахо", "나바호어", "納瓦荷文", "纳瓦霍语", "Navajo", "Navaho", "Navajo", "Nawaho", "Navaho dili", "النافاجو", "Navažština", "Navahó", "Νάβαχο", "Navajo", "นาวาโฮ", "Tiếng Navajo", "Navajo", "Навахо"}},
    {"nr nbl", {"Sør-ndebele", "South Ndebele", "Ndebele meridional", "Ndébélé du Sud", "Süd-Ndebele", "Ndebele do sul", "Ndebele del sud", "南ンデベレ語", "Zuid-Ndbele", "Южный ндебеле", "남부 은데벨레어", "南地畢列文", "南恩德贝勒语", "Etelä-ndebele", "Sydndebele", "Sydndebele", "Ndebele południowy", "Güney Ndebele", "النديبيل الجنوبي", "Ndebele (Jižní Afrika)", "Déli ndebele", "Νότια Ντεμπέλε", "Ndebele de sud", "เอ็นเดเบเลใต้", "Tiếng Ndebele Miền Nam", "Ndebele Selatan", "Ндебелє південна"}},
    {"nd nde", {"Nord-ndebele", "North Ndebele", "Ndebele septentrional", "Ndébélé du Nord", "Nord-Ndebele", "Ndebele do norte", "Ndebele del nord", "北ンデベレ語", "Noord-Ndebele", "Северный ндебеле", "북부 은데벨레어", "北地畢列文", "北恩德贝勒语", "Pohjois-ndebele", "Nordndebele", "Nordndebele", "Ndebele północny", "Kuzey Ndebele", "النديبيل الشمالية", "Ndebele (Zimbabwe)", "Északi ndebele", "Βόρεια Ντεμπέλε", "Ndebele de nord", "เอ็นเดเบเลเหนือ", "Tiếng Ndebele Miền Bắc", "Ndebele Utara", "Північна ндебеле"}},
    {"ng ndo", {"Ndonga", "Ndonga", "Ndonga", "Ndonga", "Ndonga", "Dongo", "Ndonga", "ンドンガ語", "Ndonga", "Ндонга", "느동가어", "恩東加文", "恩东加语", "Ndonga", "Ndonga", "Ndonga", "Ndonga", "Ndonga", "الندونجا", "Ndondština", "Ndonga", "Ντόνγκα", "Ndonga", "ดองกา", "Tiếng Ndonga", "Ndonga", "Ндонга"}},
    {"ne nep", {"Nepali", "Nepali", "Nepalí", "Népalais", "Nepalesisch", "Nepalês", "Nepalese", "ネパール語", "Nepalees", "Непальский", "네팔어", "尼泊爾文", "尼泊尔语", "Nepali", "Nepalesiska", "Nepalesisk", "Nepalski", "Nepalce", "النيبالية", "Nepálština", "Nepáli", "Νεπαλικά", "Nepaleză", "เนปาล", "Tiếng Nepal", "Nepali", "Непальська"}},
    {"nl nld dut", {"Nederlandsk", "Dutch", "Neerlandés", "Néerlandais", "Niederländisch", "Holandês", "Olandese", "オランダ語", "Nederlands", "Нидерландский", "네덜란드어", "荷蘭文", "荷兰语", "Hollanti", "Nederländska", "Nederlandsk", "Niderlandzki", "Felemenkçe", "الهولندية", "Nizozemština", "Holland", "Ολλανδικά", "Neerlandeză", "ดัตช์", "Tiếng Hà Lan", "Belanda", "Нідерландська"}},
    {"nn nno", {"Norsk nynorsk", "Norwegian Nynorsk", "Noruego nynorsk", "Norvégien nynorsk", "Norwegisch (Nynorsk)", "Nynorsk norueguês", "Norvegese nynorsk", "ノルウェー語(ニーノシュク)", "Noors - Nynorsk", "Нюнорск", "노르웨이어(니노르스크)", "新挪威文", "挪威尼诺斯克语", "Norjan nynorsk", "Nynorska", "Nynorsk", "Norweski (nynorsk)", "Norveççe Nynorsk", "النرويجية نينورسك", "Norština (nynorsk)", "Norvég (nynorsk)", "Νορβηγικά Νινόρσκ", "Norvegiană nynorsk", "นอร์เวย์นีนอสก์", "Tiếng Na Uy (Nynorsk)", "Nynorsk Norwegia", "Норвезька (нюношк)"}},
    {"nb nob", {"Norsk bokmål", "Norwegian Bokmål", "Noruego bokmal", "Norvégien bokmål", "Norwegisch (Bokmål)", "Bokmål norueguês", "Norvegese bokmål", "ノルウェー語(ブークモール)", "Noors - Bokmål", "Норвежский букмол", "노르웨이어(보크말)", "書面挪威文", "书面挪威语", "Norjan bokmål", "Norskt bokmål", "Bokmål", "Norweski (bokmål)", "Norveççe Bokmål", "النرويجية بوكمال", "Norština (bokmål)", "Norvég (bokmål)", "Νορβηγικά Μποκμάλ", "Norvegiană bokmål", "นอร์เวย์บุคมอล", "Tiếng Na Uy (Bokmål)", "Bokmål Norwegia", "Норвезька (букмол)"}},
    {"no nor", {"Norsk", "Norwegian", "Noruego", "Norvégien", "Norwegisch", "Norueguês", "Norvegese", "ノルウェー語", "Noors", "Норвежский", "노르웨이어", "挪威文", "挪威语", "Norja", "Norska", "Norsk", "Norweski", "Norveççe", "النرويجية", "Norština", "Norvég", "Νορβηγικά", "Norvegiană", "นอร์เวย์", "Tiếng Na Uy", "Norwegia", "Норвезька"}},
    {"ny nya", {"Nyanja", "Nyanja", "Nyanja", "Chewa", "Nyanja", "Nianja", "Nyanja", "ニャンジャ語", "Nyanja", "Ньянджа", "냔자어", "尼揚賈文", "齐切瓦语", "Njandža", "Nyanja", "Nyanja", "Njandża", "Nyanja", "النيانجا", "Ňandžština", "Nyandzsa", "Νιάντζα", "Nyanja", "เนียนจา", "Tiếng Nyanja", "Nyanja", "Ньянджа"}},
    {"oc oci", {"Oksitansk", "Occitan", "Occitano", "Occitan", "Okzitanisch", "Occitânico", "Occitano", "オック語", "Occitaans", "Окситанский", "오크어", "奧克西坦文", "奥克语", "Oksitaani", "Occitanska", "Occitansk", "Oksytański", "Oksitan dili", "الأوكسيتانية", "Okcitánština", "Okszitán", "Οξιτανικά", "Occitană", "อ็อกซิตัน", "Tiếng Occitan", "Ositania", "Окситанська"}},
    {"oj oji", {"Ojibwa", "Ojibwa", "Ojibwa", "Ojibwa", "Ojibwa", "Ojibwa", "Ojibwa", "オジブウェー語", "Ojibwa", "Оджибва", "오지브와어", "奧杰布瓦文", "奥吉布瓦语", "Odžibwa", "Odjibwa", "Ojibwa", "Odżibwa", "Ojibva dili", "الأوجيبوا", "Odžibvejština", "Ojibva", "Οζιβίγουα", "Ojibwa", "โอจิบวา", "Tiếng Ojibwa", "Ojibwa", "Оджібва"}},
    {"or ori", {"Odia", "Odia", "Oriya", "Odia", "Oriya", "Oriá", "Odia", "オディア語", "Odia", "Ория", "오리야어", "歐迪亞文", "奥里亚语", "Orija", "Oriya", "Oriya", "Orija", "Oriya dili", "الأورية", "Urijština", "Odia", "Όντια", "Odia", "โอดิยา", "Tiếng Odia", "Oriya", "Одія"}},
    {"om orm", {"Oromo", "Oromo", "Oromo", "Oromo", "Oromo", "Oromo", "Oromo", "オロモ語", "Afaan Oromo", "Оромо", "오로모어", "奧羅莫文", "奥罗莫语", "Oromo", "Oromo", "Oromo", "Oromo", "Oromo dili", "الأورومية", "Oromština", "Oromo", "Ορόμο", "Oromo", "โอโรโม", "Tiếng Oromo", "Oromo", "Оромо"}},
    {"os oss", {"Ossetisk", "Ossetic", "Osético", "Ossète", "Ossetisch", "Osseto", "Ossetico", "オセット語", "Ossetisch", "Осетинский", "오세트어", "奧塞提文", "奥塞梯语", "Osseetti", "Ossetiska", "Ossetisk", "Osetyjski", "Osetçe", "الأوسيتيك", "Osetština", "Oszét", "Οσετικά", "Osetă", "ออสเซเตีย", "Tiếng Ossetic", "Ossetia", "Осетинська"}},
    {"pa pan", {"Panjabi", "Punjabi", "Punyabí", "Pendjabi", "Punjabi", "Panjabi", "Punjabi", "パンジャブ語", "Punjabi", "Панджаби", "펀잡어", "旁遮普文", "旁遮普语", "Pandžabi", "Punjabi", "Punjabi", "Pendżabski", "Pencapça", "البنجابية", "Paňdžábština", "Pandzsábi", "Παντζαπικά", "Punjabi", "ปัญจาบ", "Tiếng Punjab", "Punjabi", "Панджабі"}},
    {"pi pli", {"Pali", "Pali", "Pali", "Pali", "Pali", "Páli", "Pali", "パーリ語", "Pali", "Пали", "팔리어", "巴利文", "巴利语", "Paali", "Pali", "Pali", "Palijski", "Pali", "البالية", "Pálí", "Pali", "Πάλι", "Pali", "บาลี", "Tiếng Pali", "Pali", "Палі"}},
    {"pl pol", {"Polsk", "Polish", "Polaco", "Polonais", "Polnisch", "Polonês", "Polacco", "ポーランド語", "Pools", "Польский", "폴란드어", "波蘭文", "波兰语", "Puola", "Polska", "Polsk", "Polski", "Lehçe", "البولندية", "Polština", "Lengyel", "Πολωνικά", "Poloneză", "โปแลนด์", "Tiếng Ba Lan", "Polski", "Польська"}},
    {"pt por", {"Portugisisk", "Portuguese", "Portugués", "Portugais", "Portugiesisch", "Português", "Portoghese", "ポルトガル語", "Portugees", "Португальский", "포르투갈어", "葡萄牙文", "葡萄牙语", "Portugali", "Portugisiska", "Portugisisk", "Portugalski", "Portekizce", "البرتغالية", "Portugalština", "Portugál", "Πορτογαλικά", "Portugheză", "โปรตุเกส", "Tiếng Bồ Đào Nha", "Portugis", "Португальська"}},
    {"ps pus", {"Pashto", "Pashto", "Pastún", "Pachto", "Paschtu", "Pashto", "Pashto", "パシュトゥー語", "Pasjtoe", "Пушту", "파슈토어", "普什圖文", "普什图语", "Paštu", "Afghanska", "Pashto", "Paszto", "Peştuca", "البشتو", "Paštština", "Pastu", "Πάστο", "Paștună", "พัชโต", "Tiếng Pashto", "Pashto", "Пушту"}},
    {"qu que", {"Quechua", "Quechua", "Quechua", "Quechua", "Quechua", "Quíchua", "Quechua", "ケチュア語", "Quechua", "Кечуа", "케추아어", "蓋楚瓦文", "克丘亚语", "Ketšua", "Quechua", "Quechua", "Keczua", "Keçuva dili", "كيشوا", "Kečuánština", "Kecsua", "Κέτσουα", "Quechua", "เคชวา", "Tiếng Quechua", "Quechua", "Кечуа"}},
    {"rm roh", {"Retoromansk", "Romansh", "Romanche", "Romanche", "Rätoromanisch", "Romanche", "Romancio", "ロマンシュ語", "Reto-Romaans", "Романшский", "로만시어", "羅曼斯文", "罗曼什语", "Retoromaani", "Rätoromanska", "Rætoromansk", "Retoromański", "Romanşça", "الرومانشية", "Rétorománština", "Rétoromán", "Ρομανικά", "Romanșă", "โรแมนซ์", "Tiếng Romansh", "Reto-Roman", "Ретороманська"}},
    {"ro ron rum", {"Rumensk", "Romanian", "Rumano", "Roumain", "Rumänisch", "Romeno", "Rumeno", "ルーマニア語", "Roemeens", "Румынский", "루마니아어", "羅馬尼亞文", "罗马尼亚语", "Romania", "Rumänska", "Rumænsk", "Rumuński", "Rumence", "الرومانية", "Rumunština", "Román", "Ρουμανικά", "Română", "โรมาเนีย", "Tiếng Romania", "Rumania", "Румунська"}},
    {"rn run", {"Rundi", "Rundi", "Kirundi", "Roundi", "Rundi", "Rundi", "Rundi", "ルンディ語", "Kirundi", "Рунди", "룬디어", "隆迪文", "隆迪语", "Rundi", "Rundi", "Rundi", "Rundi", "Kirundi", "الرندي", "Kirundština", "Kirundi", "Ρούντι", "Kirundi", "บุรุนดี", "Tiếng Rundi", "Rundi", "Рунді"}},
    {"ru rus", {"Russisk", "Russian", "Ruso", "Russe", "Russisch", "Russo", "Russo", "ロシア語", "Russisch", "Русский", "러시아어", "俄文", "俄语", "Venäjä", "Ryska", "Russisk", "Rosyjski", "Rusça", "الروسية", "Ruština", "Orosz", "Ρωσικά", "Rusă", "รัสเซีย", "Tiếng Nga", "Rusia", "Російська"}},
    {"sg sag", {"Sango", "Sango", "Sango", "Sango", "Sango", "Sango", "Sango", "サンゴ語", "Sango", "Санго", "산고어", "桑戈文", "桑戈语", "Sango", "Sango", "Sango", "Sango", "Sango", "السانجو", "Sangština", "Szangó", "Σάνγκο", "Sango", "ซันโก", "Tiếng Sango", "Sango", "Санго"}},
    {"sa san", {"Sanskrit", "Sanskrit", "Sánscrito", "Sanskrit", "Sanskrit", "Sânscrito", "Sanscrito", "サンスクリット語", "Sanskriet", "Санскрит", "산스크리트어", "梵文", "梵语", "Sanskrit", "Sanskrit", "Sanskrit", "Sanskryt", "Sanskrit", "السنسكريتية", "Sanskrt", "Szanszkrit", "Σανσκριτικά", "Sanscrită", "สันสกฤต", "Tiếng Phạn", "Sanskerta", "Санскрит"}},
    {"si sin", {"Singalesisk", "Sinhala", "Cingalés", "Cingalais", "Singhalesisch", "Cingalês", "Singalese", "シンハラ語", "Singalees", "Сингальский", "싱할라어", "僧伽羅文", "僧伽罗语", "Sinhala", "Singalesiska", "Singalesisk", "Syngaleski", "Sinhali dili", "السنهالية", "Sinhálština", "Szingaléz", "Σινχαλεζικά", "Singhaleză", "สิงหล", "Tiếng Sinhala", "Sinhala", "Сингальська"}},
    {"sk slk slo", {"Slovakisk", "Slovak", "Eslovaco", "Slovaque", "Slowakisch", "Eslovaco", "Slovacco", "スロバキア語", "Slowaaks", "Словацкий", "슬로바키아어", "斯洛伐克文", "斯洛伐克语", "Slovakki", "Slovakiska", "Slovakisk", "Słowacki", "Slovakça", "السلوفاكية", "Slovenština", "Szlovák", "Σλοβακικά", "Slovacă", "สโลวัก", "Tiếng Slovak", "Slovak", "Словацька"}},
    {"sl slv", {"Slovensk", "Slovenian", "Esloveno", "Slovène", "Slowenisch", "Esloveno", "Sloveno", "スロベニア語", "Sloveens", "Словенский", "슬로베니아어", "斯洛維尼亞文", "斯洛文尼亚语", "Sloveeni", "Slovenska", "Slovensk", "Słoweński", "Slovence", "السلوفانية", "Slovinština", "Szlovén", "Σλοβενικά", "Slovenă", "สโลวีเนีย", "Tiếng Slovenia", "Slovenia", "Словенська"}},
    {"se sme", {"Nordsamisk", "Northern Sami", "Sami septentrional", "Same du Nord", "Nordsamisch", "Sami setentrional", "Sami del nord", "北サーミ語", "Noord-Samisch", "Северносаамский", "북부 사미어", "北薩米文", "北方萨米语", "Pohjoissaame", "Nordsamiska", "Nordsamisk", "Północnolapoński", "Kuzey Laponcası", "سامي الشمالية", "Sámština (severní)", "Északi számi", "Βόρεια Σάμι", "Sami de nord", "ซามิเหนือ", "Tiếng Sami Miền Bắc", "Sami Utara", "Північносаамська"}},
    {"sm smo", {"Samoansk", "Samoan", "Samoano", "Samoan", "Samoanisch", "Samoano", "Samoano", "サモア語", "Samoaans", "Самоанский", "사모아어", "薩摩亞文", "萨摩亚语", "Samoa", "Samoanska", "Samoansk", "Samoański", "Samoa dili", "الساموائية", "Samojština", "Szamoai", "Σαμοανά", "Samoană", "ซามัว", "Tiếng Samoa", "Samoa", "Самоанська"}},
    {"sn sna", {"Shona", "Shona", "Shona", "Shona", "Shona", "Xona", "Shona", "ショナ語", "Shona", "Шона", "쇼나어", "紹納文", "绍纳语", "Šona", "Shona", "Shona", "Shona", "Şona dili", "الشونا", "Šonština", "Sona", "Σόνα", "Shona", "โชนา", "Tiếng Shona", "Shona", "Шона"}},
    {"sd snd", {"Sindhi", "Sindhi", "Sindi", "Sindhi", "Sindhi", "Sindi", "Sindhi", "シンド語", "Sindhi", "Синдхи", "신디어", "信德文", "信德语", "Sindhi", "Sindhi", "Sindhi", "Sindhi", "Sindhi dili", "السندية", "Sindhština", "Szindhi", "Σίντι", "Sindhi", "สินธิ", "Tiếng Sindhi", "Sindhi", "Синдхі"}},
    {"so som", {"Somali", "Somali", "Somalí", "Somali", "Somali", "Somali", "Somalo", "ソマリ語", "Somalisch", "Сомали", "소말리아어", "索馬利文", "索马里语", "Somali", "Somaliska", "Somali", "Somalijski", "Somalice", "الصومالية", "Somálština", "Szomáli", "Σομαλικά", "Somaleză", "โซมาลี", "Tiếng Somali", "Somalia", "Сомалі"}},
    {"st sot", {"Sør-sotho", "Southern Sotho", "Sotho meridional", "Sotho du Sud", "Süd-Sotho", "Soto do sul", "Sotho del sud", "南部ソト語", "Zuid-Sotho", "Южный сото", "남부 소토어", "塞索托文", "南索托语", "Eteläsotho", "Sydsotho", "Sydsotho", "Sotho południowy", "Güney Sotho dili", "السوتو الجنوبية", "Sotština (jižní)", "Déli szeszotó", "Νότια Σόθο", "Sesotho", "โซโทใต้", "Tiếng Sotho Miền Nam", "Sotho Selatan", "Південна сото"}},
    {"es spa", {"Spansk", "Spanish", "Español", "Espagnol", "Spanisch", "Espanhol", "Spagnolo", "スペイン語", "Spaans", "Испанский", "스페인어", "西班牙文", "西班牙语", "Espanja", "Spanska", "Spansk", "Hiszpański", "İspanyolca", "الإسبانية", "Španělština", "Spanyol", "Ισπανικά", "Spaniolă", "สเปน", "Tiếng Tây Ban Nha", "Spanyol", "Іспанська"}},
    {"sq sqi alb", {"Albansk", "Albanian", "Albanés", "Albanais", "Albanisch", "Albanês", "Albanese", "アルバニア語", "Albanees", "Албанский", "알바니아어", "阿爾巴尼亞文", "阿尔巴尼亚语", "Albania", "Albanska", "Albansk", "Albański", "Arnavutça", "الألبانية", "Albánština", "Albán", "Αλβανικά", "Albaneză", "แอลเบเนีย", "Tiếng Albania", "Albania", "Албанська"}},
    {"sc srd", {"Sardisk", "Sardinian", "Sardo", "Sarde", "Sardisch", "Sardo", "Sardo", "サルデーニャ語", "Sardijns", "Сардинский", "사르디니아어", "撒丁文", "萨丁语", "Sardi", "Sardinska", "Sardinsk", "Sardyński", "Sardunya dili", "السردينية", "Sardština", "Szardíniai", "Σαρδηνιακά", "Sardiniană", "ซาร์เดญา", "Tiếng Sardinia", "Sardinia", "Сардинська"}},
    {"sr srp", {"Serbisk", "Serbian", "Serbio", "Serbe", "Serbisch", "Sérvio", "Serbo", "セルビア語", "Servisch", "Сербский", "세르비아어", "塞爾維亞文", "塞尔维亚语", "Serbia", "Serbiska", "Serbisk", "Serbski", "Sırpça", "الصربية", "Srbština", "Szerb", "Σερβικά", "Sârbă", "เซอร์เบีย", "Tiếng Serbia", "Serbia", "Сербська"}},
    {"ss ssw", {"Swati", "Swati", "Suazi", "Swati", "Swazi", "Suázi", "Swati", "スワジ語", "Swazi", "Свази", "시스와티어", "斯瓦特文", "斯瓦蒂语", "Swazi", "Swati", "Swati", "Suazi", "Sisvati", "السواتي", "Siswatština", "Sziszuati", "Σουάτι", "Swati", "สวาติ", "Tiếng Swati", "Swati", "Сисваті"}},
    {"su sun", {"Sundanesisk", "Sundanese", "Sundanés", "Soundanais", "Sundanesisch", "Sundanês", "Sundanese", "スンダ語", "Soendanees", "Сунданский", "순다어", "巽他文", "巽他语", "Sunda", "Sundanesiska", "Sundanesisk", "Sundajski", "Sunda dili", "السوندانية", "Sundština", "Szundanéz", "Σουνδανικά", "Sundaneză", "ซุนดา", "Tiếng Sunda", "Sunda", "Сунданська"}},
    {"sw swa", {"Swahili", "Swahili", "Suajili", "Swahili", "Suaheli", "Suaíli", "Swahili", "スワヒリ語", "Swahili", "Суахили", "스와힐리어", "史瓦希里文", "斯瓦希里语", "Swahili", "Swahili", "Swahili", "Suahili", "Svahili dili", "السواحلية", "Svahilština", "Szuahéli", "Σουαχίλι", "Swahili", "สวาฮีลี", "Tiếng Swahili", "Swahili", "Суахілі"}},
    {"sv swe", {"Svensk", "Swedish", "Sueco", "Suédois", "Schwedisch", "Sueco", "Svedese", "スウェーデン語", "Zweeds", "Шведский", "스웨덴어", "瑞典文", "瑞典语", "Ruotsi", "Svenska", "Svensk", "Szwedzki", "İsveççe", "السويدية", "Švédština", "Svéd", "Σουηδικά", "Suedeză", "สวีเดน", "Tiếng Thụy Điển", "Swedia", "Шведська"}},
    {"ty tah", {"Tahitisk", "Tahitian", "Tahitiano", "Tahitien", "Tahitisch", "Taitiano", "Taitiano", "タヒチ語", "Tahitiaans", "Таитянский", "타히티어", "大溪地文", "塔希提语", "Tahiti", "Tahitiska", "Tahitiansk", "Tahitański", "Tahiti dili", "التاهيتية", "Tahitština", "Tahiti", "Ταϊτιανά", "Tahitiană", "ตาฮิตี", "Tiếng Tahiti", "Tahiti", "Таїтянська"}},
    {"ta tam", {"Tamil", "Tamil", "Tamil", "Tamoul", "Tamil", "Tâmil", "Tamil", "タミル語", "Tamil", "Тамильский", "타밀어", "坦米爾文", "泰米尔语", "Tamili", "Tamil", "Tamil", "Tamilski", "Tamilce", "التاميلية", "Tamilština", "Tamil", "Ταμιλικά", "Tamilă", "ทมิฬ", "Tiếng Tamil", "Tamil", "Тамільська"}},
    {"tt tat", {"Tatarisk", "Tatar", "Tártaro", "Tatar", "Tatarisch", "Tártaro", "Tataro", "タタール語", "Tataars", "Татарский", "타타르어", "韃靼文", "鞑靼语", "Tataari", "Tatariska", "Tatarisk", "Tatarski", "Tatarca", "التترية", "Tatarština", "Tatár", "Ταταρικά", "Tătară", "ตาตาร์", "Tiếng Tatar", "Tatar", "Татарська"}},
    {"te tel", {"Telugu", "Telugu", "Telugu", "Télougou", "Telugu", "Télugo", "Telugu", "テルグ語", "Telugu", "Телугу", "텔루구어", "泰盧固文", "泰卢固语", "Telugu", "Telugu", "Telugu", "Telugu", "Telugu dili", "التيلوغوية", "Telugština", "Telugu", "Τελούγκου", "Telugu", "เตลูกู", "Tiếng Telugu", "Telugu", "Телугу"}},
    {"tg tgk", {"Tadsjikisk", "Tajik", "Tayiko", "Tadjik", "Tadschikisch", "Tadjique", "Tagico", "タジク語", "Tadzjieks", "Таджикский", "타지크어", "塔吉克文", "塔吉克语", "Tadžikki", "Tadzjikiska", "Tadsjikisk", "Tadżycki", "Tacikçe", "الطاجيكية", "Tádžičtina", "Tadzsik", "Τατζικικά", "Tadjică", "ทาจิก", "Tiếng Tajik", "Tajik", "Таджицька"}},
    {"tl tgl", {"Tagalog", "Tagalog", "Tagalo", "Tagalog", "Tagalog", "Tagalo", "Tagalog", "タガログ語", "Tagalog", "Тагалог", "타갈로그어", "塔加路族文", "他加禄语", "Tagalog", "Tagalog", "Tagalog", "Tagalski", "Tagalogca", "التاغالوغية", "Tagalog", "Tagalog", "Τάγκαλογκ", "Tagalog", "ตากาล็อก", "Tiếng Tagalog", "Tagalog", "Тагальська"}},
    {"th tha", {"Thai", "Thai", "Tailandés", "Thaï", "Thailändisch", "Tailandês", "Thailandese", "タイ語", "Thai", "Тайский", "태국어", "泰文", "泰语", "Thai", "Thailändska", "Thai", "Tajski", "Tayca", "التايلاندية", "Thajština", "Thai", "Ταϊλανδικά", "Thailandeză", "ไทย", "Tiếng Thái", "Thai", "Тайська"}},
    {"ti tir", {"Tigrinja", "Tigrinya", "Tigriña", "Tigrigna", "Tigrinya", "Tigrínia", "Tigrino", "ティグリニア語", "Tigrinya", "Тигринья", "티그리냐어", "提格利尼亞文", "提格利尼亚语", "Tigrinja", "Tigrinja", "Tigrinya", "Tigrinia", "Tigrinya dili", "التغرينية", "Tigrinijština", "Tigrinya", "Τιγκρινικά", "Tigrină", "ติกริญญา", "Tiếng Tigrinya", "Tigrinya", "Тигринья"}},
    {"to ton", {"Tongansk", "Tongan", "Tongano", "Tongien", "Tongaisch", "Tonganês", "Tongano", "トンガ語", "Tongaans", "Тонганский", "통가어", "東加文", "汤加语", "Tonga", "Tonganska", "Tongansk", "Tonga", "Tonga dili", "التونغية", "Tongánština", "Tongai", "Τονγκανικά", "Tongană", "ตองกา", "Tiếng Tonga", "Tonga", "Тонганська"}},
    {"tn tsn", {"Setswana", "Tswana", "Setsuana", "Tswana", "Tswana", "Tswana", "Tswana", "ツワナ語", "Tswana", "Тсвана", "츠와나어", "塞茲瓦納文", "茨瓦纳语", "Tswana", "Tswana", "Tswana", "Setswana", "Setsvana", "التسوانية", "Setswanština", "Szecsuáni", "Τσουάνα", "Setswana", "สวานา", "Tiếng Tswana", "Tswana", "Тсвана"}},
    {"ts tso", {"Tsonga", "Tsonga", "Tsonga", "Tsonga", "Tsonga", "Tsonga", "Tsonga", "ツォンガ語", "Tsonga", "Тсонга", "총가어", "特松加文", "聪加语", "Tsonga", "Tsonga", "Tsonga", "Tsonga", "Tsonga", "السونجا", "Tsonga", "Conga", "Τσόνγκα", "Tsonga", "ซองกา", "Tiếng Tsonga", "Tsonga", "Тсонга"}},
    {"tk tuk", {"Turkmensk", "Turkmen", "Turcomano", "Turkmène", "Turkmenisch", "Turcomeno", "Turcomanno", "トルクメン語", "Turkmeens", "Туркменский", "투르크멘어", "土庫曼文", "土库曼语", "Turkmeeni", "Turkmeniska", "Turkmensk", "Turkmeński", "Türkmence", "التركمانية", "Turkmenština", "Türkmén", "Τουρκμενικά", "Turkmenă", "เติร์กเมน", "Tiếng Turkmen", "Turkmen", "Туркменська"}},
    {"tr tur", {"Tyrkisk", "Turkish", "Turco", "Turc", "Türkisch", "Turco", "Turco", "トルコ語", "Turks", "Турецкий", "튀르키예어", "土耳其文", "土耳其语", "Turkki", "Turkiska", "Tyrkisk", "Turecki", "Türkçe", "التركية", "Turečtina", "Török", "Τουρκικά", "Turcă", "ตุรกี", "Tiếng Thổ Nhĩ Kỳ", "Turki", "Турецька"}},
    {"tw twi", {"Twi", "Twi", "Twi", "Twi", "Twi", "Twi", "Ci", "トウィ語", "Twi", "Тви", "트위어", "特威文", "契维语", "Twi", "Twi", "Twi", "Twi", "Tvi", "التوي", "Twi", "Twi", "Τούι", "Twi", "ทวิ", "Tiếng Twi", "Twi", "Тві"}},
    {"ug uig", {"Uigurisk", "Uyghur", "Uigur", "Ouïghour", "Uigurisch", "Uigur", "Uiguro", "ウイグル語", "Oeigoers", "Уйгурский", "위구르어", "維吾爾文", "维吾尔语", "Uiguuri", "Uiguriska", "Uygurisk", "Ujgurski", "Uygurca", "الأويغورية", "Ujgurština", "Ujgur", "Ουιγουρικά", "Uigură", "อุยกูร์", "Tiếng Uyghur", "Uyghur", "Уйгурська"}},
    {"uk ukr", {"Ukrainsk", "Ukrainian", "Ucraniano", "Ukrainien", "Ukrainisch", "Ucraniano", "Ucraino", "ウクライナ語", "Oekraïens", "Украинский", "우크라이나어", "烏克蘭文", "乌克兰语", "Ukraina", "Ukrainska", "Ukrainsk", "Ukraiński", "Ukraynaca", "الأوكرانية", "Ukrajinština", "Ukrán", "Ουκρανικά", "Ucraineană", "ยูเครน", "Tiếng Ukraina", "Ukraina", "Українська"}},
    {"ur urd", {"Urdu", "Urdu", "Urdu", "Ourdou", "Urdu", "Urdu", "Urdu", "ウルドゥー語", "Urdu", "Урду", "우르두어", "烏都文", "乌尔都语", "Urdu", "Urdu", "Urdu", "Urdu", "Urduca", "الأوردية", "Urdština", "Urdu", "Ούρντου", "Urdu", "อูรดู", "Tiếng Urdu", "Urdu", "Урду"}},
    {"uz uzb", {"Usbekisk", "Uzbek", "Uzbeko", "Ouzbek", "Usbekisch", "Uzbeque", "Uzbeco", "ウズベク語", "Oezbeeks", "Узбекский", "우즈베크어", "烏茲別克文", "乌兹别克语", "Uzbekki", "Uzbekiska", "Usbekisk", "Uzbecki", "Özbekçe", "الأوزبكية", "Uzbečtina", "Üzbég", "Ουζμπεκικά", "Uzbecă", "อุซเบก", "Tiếng Uzbek", "Uzbek", "Узбецька"}},
    {"ve ven", {"Venda", "Venda", "Venda", "Venda", "Venda", "Venda", "Venda", "ベンダ語", "Venda", "Венда", "벤다어", "溫達文", "文达语", "Venda", "Venda", "Venda", "Venda", "Venda dili", "الفيندا", "Venda", "Venda", "Βέντα", "Venda", "เวนดา", "Tiếng Venda", "Venda", "Венда"}},
    {"vi vie", {"Vietnamesisk", "Vietnamese", "Vietnamita", "Vietnamien", "Vietnamesisch", "Vietnamita", "Vietnamita", "ベトナム語", "Vietnamees", "Вьетнамский", "베트남어", "越南文", "越南语", "Vietnam", "Vietnamesiska", "Vietnamesisk", "Wietnamski", "Vietnamca", "الفيتنامية", "Vietnamština", "Vietnámi", "Βιετναμικά", "Vietnameză", "เวียดนาม", "Tiếng Việt", "Vietnam", "Вʼєтнамська"}},
    {"vo vol", {"Volapyk", "Volapük", "Volapük", "Volapük", "Volapük", "Volapuque", "Volapük", "ヴォラピュク語", "Volapük", "Волапюк", "볼라퓌크어", "沃拉普克文", "沃拉普克语", "Volapük", "Volapük", "Volapyk", "Wolapik", "Volapük", "لغة الفولابوك", "Volapük", "Volapük", "Βολαπιούκ", "Volapuk", "โวลาพึค", "Tiếng Volapük", "Volapuk", "Волапюк"}},
    {"wa wln", {"Vallonsk", "Walloon", "Valón", "Wallon", "Wallonisch", "Valão", "Vallone", "ワロン語", "Waals", "Валлонский", "왈론어", "瓦隆文", "瓦隆语", "Valloni", "Vallonska", "Vallonsk", "Waloński", "Valonca", "الولونية", "Valonština", "Vallon", "Βαλλωνικά", "Valonă", "วอลลูน", "Tiếng Walloon", "Walloon", "Валлонська"}},
    {"wo wol", {"Wolof", "Wolof", "Wólof", "Wolof", "Wolof", "Uolofe", "Wolof", "ウォロフ語", "Wolof", "Волоф", "월로프어", "沃洛夫文", "沃洛夫语", "Wolof", "Wolof", "Wolof", "Wolof", "Volofça", "الولوفية", "Wolofština", "Volof", "Γουόλοφ", "Wolof", "โวลอฟ", "Tiếng Wolof", "Wolof", "Волоф"}},
    {"xh xho", {"Xhosa", "Xhosa", "Xhosa", "Xhosa", "Xhosa", "Xhosa", "Xhosa", "コサ語", "Xhosa", "Коса", "코사어", "科薩文", "科萨语", "Xhosa", "Xhosa", "Xhosa", "Khosa", "Zosa dili", "الخوسا", "Xhoština", "Xhosza", "Κόσα", "Xhosa", "คะห์โอซา", "Tiếng Xhosa", "Xhosa", "Кхоса"}},
    {"yi yid", {"Jiddisk", "Yiddish", "Yidis", "Yiddish", "Jiddisch", "Iídiche", "Yiddish", "イディッシュ語", "Jiddisch", "Идиш", "이디시어", "意第緒文", "意第绪语", "Jiddiš", "Jiddisch", "Jiddisch", "Jidysz", "Yidiş", "اليديشية", "Jidiš", "Jiddis", "Γίντις", "Idiș", "ยิดดิช", "Tiếng Yiddish", "Yiddish", "Їдиш"}},
    {"yo yor", {"Joruba", "Yoruba", "Yoruba", "Yoruba", "Yoruba", "Iorubá", "Yoruba", "ヨルバ語", "Yoruba", "Йоруба", "요루바어", "約魯巴文", "约鲁巴语", "Joruba", "Yoruba", "Yoruba", "Joruba", "Yorubaca", "اليوروبا", "Jorubština", "Joruba", "Γιορούμπα", "Yoruba", "โยรูบา", "Tiếng Yoruba", "Yoruba", "Йоруба"}},
    {"za zha", {"Zhuang", "Zhuang", "Zhuang", "Zhuang", "Zhuang", "Zhuang", "Zhuang", "チワン語", "Zhuang", "Чжуань", "주앙어", "壯文", "壮语", "Zhuang", "Zhuang", "Zhuang", "Czuang", "Zhuangca", "الزهيونج", "Čuangština", "Zsuang", "Ζουάνγκ", "Zhuang", "จ้วง", "Tiếng Choang", "Zhuang", "Чжуан"}},
    {"zh zho chi", {"Kinesisk", "Chinese", "Chino", "Chinois", "Chinesisch", "Chinês", "Cinese", "中国語", "Chinees", "Китайский", "중국어", "中文", "中文", "Kiina", "Kinesiska", "Kinesisk", "Chiński", "Çince", "الصينية", "Čínština", "Kínai", "Κινεζικά", "Chineză", "จีน", "Tiếng Trung", "Tionghoa", "Китайська"}},
    {"zu zul", {"Zulu", "Zulu", "Zulú", "Zoulou", "Zulu", "Zulu", "Zulu", "ズールー語", "Zoeloe", "Зулу", "줄루어", "祖魯文", "祖鲁语", "Zulu", "Zulu", "Zulu", "Zulu", "Zuluca", "الزولو", "Zuluština", "Zulu", "Ζουλού", "Zulu", "ซูลู", "Tiếng Zulu", "Zulu", "Зулуська"}},
    {"yue", {"Kantonesisk", "Cantonese", "Cantonés", "Cantonais", "Kantonesisch", "Cantonês", "Cantonese", "広東語", "Kantonees", "Кантонский", "광둥어", "粵語", "粤语", "Kantoninkiina", "Kantonesiska", "Kantonesisk", "Kantoński", "Kantonca", "الكَنْتُونية", "Kantonština", "Kantoni", "Καντονέζικα", "Cantoneză", "กวางตุ้ง", "Tiếng Quảng Đông", "Kanton", "Кантонська"}},
    {"fil", {"Filipino", "Filipino", "Filipino", "Filipino", "Filipino", "Filipino", "Filippino", "フィリピノ語", "Filipijns", "Филиппинский", "필리핀어", "菲律賓文", "菲律宾语", "Filipino", "Filippinska", "Filippinsk", "Filipiński", "Filipince", "الفلبينية", "Filipínština", "Filippínó", "Φιλιππινικά", "Filipineză", "ฟิลิปปินส์", "Tiếng Philippines", "Filipino", "Філіппінська"}},
};

} // namespace

std::string long_date(int y, int m, int d)
{
    if (m < 1 || m > 12)
        return std::string();
    const DateFormat &f = kDates[(int)lang()];
    std::string out;
    for (const char *p = f.pattern; *p;) {
        char b[16];
        if (std::strncmp(p, "{d}", 3) == 0)
            std::snprintf(b, sizeof b, "%d", d), out += b;
        else if (std::strncmp(p, "{m}", 3) == 0)
            std::snprintf(b, sizeof b, "%d", m), out += b;
        else if (std::strncmp(p, "{M}", 3) == 0)
            out += f.months[m - 1];
        else if (std::strncmp(p, "{y}", 3) == 0)
            std::snprintf(b, sizeof b, "%d", y), out += b;
        else if (std::strncmp(p, "{b}", 3) == 0)
            std::snprintf(b, sizeof b, "%d", y + 543), out += b;
        else {
            out += *p++;
            continue;
        }
        p += 3;
    }
    return out;
}

std::string language_name(const std::string &code)
{
    std::string lc;
    for (char ch : code) {
        if (ch == '-' || ch == '_')
            break;   /* "pt-BR": the language */
        lc += (char)(ch >= 'A' && ch <= 'Z' ? ch + 32 : ch);
    }
    if (lc.empty())
        return std::string();
    for (const LanguageName &l : kLanguages) {
        const char *p = std::strstr(l.codes, lc.c_str());
        for (; p; p = std::strstr(p + 1, lc.c_str())) {
            const bool starts = p == l.codes || p[-1] == ' ', ends = p[lc.size()] == ' ' || !p[lc.size()];
            if (starts && ends) {
                const char *n = l.names[(int)lang()];
                return *n ? n : l.names[(int)Lang::English];
            }
        }
    }
    return std::string();
}

} // namespace i18n
