/*
 * Jelly5 — Jellyfin for PS5
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * What the translation tables don't hold, from the Unicode CLDR: long dates and
 * language names in the interface's language (i18n_cldr.cpp, generated by
 * scripts/i18n_cldr.py).
 */
#pragma once

#include "app/i18n.h"

#include <string>

namespace i18n {

/* "12. mars 1971", "March 12, 1971", "1971年3月12日"; empty for a month outside 1-12. */
std::string long_date(int y, int m, int d);
/* "Fransk", "French", "フランス語" from an ISO 639 code ("fr", "fra", "fre", "fr-CA");
 * empty when CLDR has no name for it. */
std::string language_name(const std::string &code);

} // namespace i18n
